import type { AdminConfigOverride } from "../utils/config";

const ADMIN_TOKEN_KEY = "velo:admin-token";
const ADMIN_ROLE_KEY = "velo:admin-role";
const API_URL = ((import.meta.env.VITE_API_URL as string | undefined) || "http://localhost:4000").replace(/\/$/, "");
export interface AdminApplicationSummary { applicationId: string; applicantType: "PERSONAL" | "BUSINESS"; status: string; applicantName: string; email: string; phone: string; loanAmount: number; totalRepayment: number; tenure: string; repaymentDate: string; dateCreated: string; dateSubmitted: string; dateUpdated: string; driveFolderUrl: string; }
export interface AdminApplicationDetail { applicationId: string; applicantType: "PERSONAL" | "BUSINESS"; status: string; createdAt: string; updatedAt: string; submittedAt: string; personalInfo: any; businessInfo: any; businessRep: any; kyc: any; financial: any; loan: any; documents: any; customerSnapshot?: any; creditReportSnapshot?: any; }
export interface AdminStats { counts: Record<string, number>; total: number; totalLoanAmount: number; totalRepayment: number; totalLoanDisbursed: number; realizedRevenue: number; awaitingRevenue: number; }

function token() { return sessionStorage.getItem(ADMIN_TOKEN_KEY); }
async function request<T>(path: string, options: RequestInit = {}): Promise<T> { const headers = new Headers(options.headers); headers.set("Content-Type", "application/json"); if (token()) headers.set("Authorization", `Bearer ${token()}`); const response = await fetch(`${API_URL}${path}`, { ...options, headers }); const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body.error || "Admin API request failed"); return body as T; }
export function getAdminToken() { return token(); }
export function setAdminToken(value: string) { sessionStorage.setItem(ADMIN_TOKEN_KEY, value); }
export function getAdminRole() { return sessionStorage.getItem(ADMIN_ROLE_KEY); }
export function setAdminRole(value: string) { sessionStorage.setItem(ADMIN_ROLE_KEY, value); }
export function clearAdminToken() { sessionStorage.removeItem(ADMIN_TOKEN_KEY); sessionStorage.removeItem(ADMIN_ROLE_KEY); }

export async function adminLogin(email: string, password: string) { const response = await request<{ ok: boolean; accessToken: string; user: { roles: string[] } }>("/api/v1/auth/admin/login", { method: "POST", body: JSON.stringify({ email, password }) }); if (response.ok) { setAdminToken(response.accessToken); setAdminRole(response.user.roles[0] || "ADMIN"); } return { ok: response.ok, token: response.accessToken, role: response.user.roles[0] || "ADMIN" }; }
export async function adminListApplications(_opts: { status?: string; type?: string; search?: string; limit?: number; offset?: number } = {}): Promise<{ total: number; applications: AdminApplicationSummary[] }> { const response = await request<{ loans: any[] }>("/api/v1/admin/loans"); const applications = (response.loans || []).map((loan) => ({ applicationId: loan.applicationId || loan.id, applicantType: (loan.customerSnapshot?.businessInfo?.businessName ? "BUSINESS" : "PERSONAL") as "PERSONAL" | "BUSINESS", status: loan.status, applicantName: loan.customerSnapshot?.fullName || "Borrower", email: loan.customerSnapshot?.email || "", phone: loan.customerSnapshot?.phone || "", loanAmount: Number(loan.amountNaira || 0), totalRepayment: Number(loan.totalRepaymentNaira || 0), tenure: `${loan.tenureDays || 0} days`, repaymentDate: loan.dueAt || "", dateCreated: loan.createdAt, dateSubmitted: loan.createdAt, dateUpdated: loan.createdAt, driveFolderUrl: "" })); return { total: applications.length, applications }; }
export async function adminGetApplication(id: string): Promise<AdminApplicationDetail> { const response = await request<{ loan: any }>(`/api/v1/admin/loans/${encodeURIComponent(id)}`); const loan = response.loan; return { applicationId: loan.applicationId || loan.id, applicantType: "PERSONAL", status: loan.status, createdAt: loan.createdAt, updatedAt: loan.updatedAt || loan.createdAt, submittedAt: loan.createdAt, personalInfo: loan.customerSnapshot?.personalInfo || {}, businessInfo: loan.customerSnapshot?.businessInfo || {}, businessRep: loan.customerSnapshot?.businessRep || {}, kyc: loan.customerSnapshot?.kyc || {}, financial: loan.customerSnapshot?.personalFinancial || loan.customerSnapshot?.businessFinancial || {}, loan, documents: {}, customerSnapshot: loan.customerSnapshot, creditReportSnapshot: loan.creditReportSnapshot }; }
export async function adminUpdateStatus(id: string, status: string) { const decision = status === "APPROVED" ? "APPROVED" : status === "REJECTED" ? "REJECTED" : "MORE_INFORMATION_REQUIRED"; const response = await request<{ loan: any }>(`/api/v1/admin/loans/${encodeURIComponent(id)}/decision`, { method: "POST", body: JSON.stringify({ decision }) }); return { ok: true, status: response.loan.status }; }
export async function adminListStats(): Promise<AdminStats> { const response = await request<{ totals: Record<string, number> }>("/api/v1/admin/summary"); return { counts: {}, total: response.totals.users || 0, totalLoanAmount: 0, totalRepayment: 0, totalLoanDisbursed: 0, realizedRevenue: 0, awaitingRevenue: response.totals.pendingPayments || 0 }; }
export async function adminSaveConfig(overrides: AdminConfigOverride) { return overrides; }
export async function adminResetConfig() { return { ok: true }; }
export async function adminCreateLoanManager(_email: string, _name: string, _appUrl: string) { return { ok: false, error: "Loan manager provisioning API is not yet enabled on the Node backend." }; }
export async function setLoanManagerPassword(_token: string, _password: string) { return { ok: false, error: "Loan manager provisioning API is not yet enabled on the Node backend." }; }
export async function requestAdminPasswordReset(_email: string) { return { ok: false, message: "Configure the Node admin password reset service before using this action." }; }
export async function resetAdminPassword(_challengeId: string, _otp: string, _password: string) { return { ok: false, message: "Configure the Node admin password reset service before using this action." }; }
