import { useState } from "react";
import { adminLogin } from "../../services/adminApi";

interface Props { onLogin: (role?: string) => void; }
export default function AdminLogin({ onLogin }: Props) {
  const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  async function submit(event: React.FormEvent) { event.preventDefault(); setError(""); setBusy(true); try { const response = await adminLogin(email.trim(), password); if (!response.ok) throw new Error("Invalid administrator credentials."); onLogin(response.role); } catch (err) { setError(err instanceof Error ? err.message : "Unable to sign in"); } finally { setBusy(false); } }
  return <div className="mx-auto max-w-md py-8"><div className="mb-6 text-center"><div className="mx-auto mb-3 inline-flex h-14 w-14 items-center justify-center rounded-2xl bg-velo-50 text-velo-600"><svg width="26" height="26" viewBox="0 0 24 24" fill="none" aria-hidden="true"><rect x="3" y="11" width="18" height="11" rx="2" stroke="currentColor" strokeWidth="1.8"/><path d="M7 11V7a5 5 0 0110 0v4" stroke="currentColor" strokeWidth="1.8"/></svg></div><h1 className="text-xl font-bold text-velo-900">Admin Portal Login</h1><p className="mt-1 text-sm text-slate-500">Sign in through the Velo Node API.</p></div><form onSubmit={submit} className="velo-card space-y-4 p-5 sm:p-6"><label className="velo-label">Email address<input className="velo-input mt-1" type="email" value={email} onChange={(event) => setEmail(event.target.value)} autoComplete="username" required /></label><label className="velo-label">Password<input className="velo-input mt-1" type="password" value={password} onChange={(event) => setPassword(event.target.value)} autoComplete="current-password" required /></label>{error && <div className="rounded-lg border border-red-100 bg-red-50 p-3 text-sm text-red-700">{error}</div>}<button className="btn-primary w-full" disabled={busy}>{busy ? "Signing in…" : "Sign in"}</button></form></div>;
}
