import { useCallback, useEffect, useState } from "react";
import { adminListApplications, adminListStats, type AdminApplicationSummary, type AdminStats } from "../../services/adminApi";
import { formatNaira, formatDateLabel } from "../../utils/loanCalculator";

export default function AdminApplicationsTable({onSelect}:{onSelect:(id:string)=>void}){
 const [stats,setStats]=useState<AdminStats|null>(null);const[rows,setRows]=useState<AdminApplicationSummary[]>([]);const[total,setTotal]=useState(0);const[page,setPage]=useState(0);const[status,setStatus]=useState("");const[type,setType]=useState("");const[search,setSearch]=useState("");const[loading,setLoading]=useState(true);const[error,setError]=useState("");const size=20;
 const load=useCallback(async()=>{setLoading(true);setError("");try{const[s,l]=await Promise.all([adminListStats(),adminListApplications({status,type,search,limit:size,offset:page*size})]);setStats(s);setRows(l.applications);setTotal(l.total);}catch(e:any){setError(e?.message||"Failed to load applications.");}finally{setLoading(false);}},[status,type,search,page]);
 useEffect(()=>{setPage(0);},[status,type,search]);useEffect(()=>{const t=setTimeout(load,250);return()=>clearTimeout(t);},[load]);const pages=Math.max(1,Math.ceil(total/size));
 return <div className="space-y-5">{stats&&<div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-5 gap-3"><Card label="Total Applications" value={String(stats.total)}/><Card label="Loan Disbursed" value={formatNaira(stats.totalLoanDisbursed)}/><Card label="Current Revenue" value={formatNaira(stats.realizedRevenue)}/><Card label="Awaiting Revenue" value={formatNaira(stats.awaitingRevenue)}/><Card label="Repaid" value={String(stats.counts.REPAID||0)}/></div>}
 <div className="velo-card p-4"><div className="grid grid-cols-1 sm:grid-cols-3 gap-3"><input className="velo-input" placeholder="Search ID, name, email, phone…" value={search} onChange={e=>setSearch(e.target.value)}/><select className="velo-input" value={status} onChange={e=>setStatus(e.target.value)}><option value="">All Statuses</option>{["DRAFT","IN_PROGRESS","SUBMITTED","UNDER_REVIEW","APPROVED","REJECTED","DISBURSED","REPAID"].map(v=><option key={v} value={v}>{v.replace(/_/g," ")}</option>)}</select><select className="velo-input" value={type} onChange={e=>setType(e.target.value)}><option value="">All Types</option><option value="PERSONAL">Personal</option><option value="BUSINESS">Business</option></select></div><div className="mt-2 flex justify-between text-xs text-slate-500"><span>{total} applications · page {page+1} of {pages}</span><button className="btn-ghost text-xs" onClick={load}>Refresh</button></div></div>
 {error&&<div className="rounded-lg bg-red-50 border border-red-100 p-3 text-sm text-red-700">{error}</div>}
 {loading?<div className="velo-card p-8 text-center text-sm text-slate-500">Loading applications…</div>:<div className="velo-card overflow-hidden"><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="bg-slate-50 border-b text-left text-xs uppercase tracking-wider text-slate-500"><th className="px-4 py-3">Applicant</th><th className="px-4 py-3">Status</th><th className="px-4 py-3 text-right">Loan</th><th className="px-4 py-3 text-right">Repayment</th><th className="px-4 py-3">Repayment Date</th><th className="px-4 py-3">Submitted</th></tr></thead><tbody className="divide-y divide-slate-100">{rows.map(a=><tr key={a.applicationId} className="hover:bg-velo-50/30 cursor-pointer" onClick={()=>onSelect(a.applicationId)}><td className="px-4 py-3"><div className="font-medium text-velo-900">{a.applicantName||"—"}</div><div className="text-xs text-slate-500 font-mono">{a.applicationId}</div></td><td className="px-4 py-3"><span className="badge bg-slate-100 text-slate-700">{a.status.replace(/_/g," ")}</span></td><td className="px-4 py-3 text-right font-semibold">{formatNaira(a.loanAmount)}</td><td className="px-4 py-3 text-right">{formatNaira(a.totalRepayment)}</td><td className="px-4 py-3 text-xs text-slate-500">{a.repaymentDate?formatDateLabel(a.repaymentDate):"—"}</td><td className="px-4 py-3 text-xs text-slate-500">{a.dateSubmitted?formatDateLabel(a.dateSubmitted):"—"}</td></tr>)}</tbody></table></div>{rows.length===0&&<div className="p-8 text-center text-sm text-slate-500">No applications match your filters.</div>}</div>}
 <div className="flex items-center justify-between"><button className="btn-secondary text-xs" disabled={page===0||loading} onClick={()=>setPage(p=>p-1)}>Previous</button><span className="text-xs text-slate-500">Page {page+1} of {pages}</span><button className="btn-secondary text-xs" disabled={page>=pages-1||loading} onClick={()=>setPage(p=>p+1)}>Next</button></div></div>;
}
function Card({label,value}:{label:string;value:string}){return <div className="rounded-xl border border-slate-100 p-3 bg-slate-50"><div className="text-[11px] font-semibold uppercase tracking-wider text-slate-500">{label}</div><div className="text-lg font-bold text-velo-900 mt-1">{value}</div></div>}
