import { useEffect, useState } from "react";
import { adminCreateAdministrator, adminDeleteAdministrator, adminListAdministrators, adminSetAdministratorStatus, type Administrator } from "../../services/adminApi";

export default function AdminAccounts() {
  const [rows, setRows] = useState<Administrator[]>([]); const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [phone, setPhone] = useState(""); const [password, setPassword] = useState(""); const [message, setMessage] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  async function load() { try { setRows((await adminListAdministrators()).administrators); } catch (err) { setError(err instanceof Error ? err.message : "Unable to load administrators"); } }
  useEffect(() => { void load(); }, []);
  async function create() { setError(""); setMessage(""); if (!name || !email || !phone || password.length < 12) { setError("Enter name, email, phone, and a password of at least 12 characters."); return; } setBusy(true); try { await adminCreateAdministrator(email, name, phone, password); setName(""); setEmail(""); setPhone(""); setPassword(""); setMessage("Administrator created. They must use OTP verification when signing in."); await load(); } catch (err) { setError(err instanceof Error ? err.message : "Unable to create administrator"); } finally { setBusy(false); } }
  return <div className="space-y-5"><div className="velo-card max-w-3xl space-y-4 p-5"><div><h2 className="text-lg font-bold text-velo-900">Administrator accounts</h2><p className="mt-1 text-sm text-slate-500">Create and control back-office administrators. Every admin login requires OTP verification.</p></div><div className="grid gap-3 sm:grid-cols-2"><input className="velo-input" placeholder="Full name" value={name} onChange={(event) => setName(event.target.value)} /><input className="velo-input" type="email" placeholder="Email" value={email} onChange={(event) => setEmail(event.target.value)} /><input className="velo-input" placeholder="Nigerian phone number" value={phone} onChange={(event) => setPhone(event.target.value)} /><input className="velo-input" type="password" placeholder="Temporary password (12+ characters)" value={password} onChange={(event) => setPassword(event.target.value)} /></div>{message && <div className="rounded-lg border border-emerald-100 bg-emerald-50 p-3 text-sm text-emerald-700">{message}</div>}{error && <div className="rounded-lg border border-red-100 bg-red-50 p-3 text-sm text-red-700">{error}</div>}<button className="btn-primary" type="button" disabled={busy} onClick={create}>{busy ? "Creating…" : "Create administrator"}</button></div><div className="velo-card divide-y divide-slate-100">{rows.map((row) => <div className="flex flex-wrap items-center justify-between gap-3 p-4" key={row.id}><div><div className="font-semibold text-velo-900">{row.fullName}</div><div className="text-xs text-slate-500">{row.email} · {row.phone}</div><span className={`badge ${row.isActive === false ? "badge-pending" : "badge-completed"}`}>{row.isActive === false ? "DEACTIVATED" : "ACTIVE"}</span></div><div className="flex gap-2"><button className="btn-ghost text-xs" onClick={async () => { await adminSetAdministratorStatus(row.id, row.isActive === false); await load(); }}>{row.isActive === false ? "Activate" : "Deactivate"}</button><button className="btn-ghost text-xs text-red-600" onClick={async () => { if (window.confirm("Delete this administrator?")) { await adminDeleteAdministrator(row.id); await load(); } }}>Delete</button></div></div>)}{!rows.length && <div className="p-6 text-sm text-slate-500">No persisted administrator accounts yet.</div>}</div></div>;
}