import { useEffect, useState } from "react";
import { adminCreateLoanManager, adminDeleteLoanManager, adminListLoanManagers, adminSetLoanManagerStatus, type LoanManager } from "../../services/adminApi";

export default function LoanManagerAdmin() {
  const [name,setName]=useState(""); const [email,setEmail]=useState(""); const [phone,setPhone]=useState(""); const [password,setPassword]=useState(""); const [managers,setManagers]=useState<LoanManager[]>([]); const [busy,setBusy]=useState(false); const [message,setMessage]=useState(""); const [error,setError]=useState("");
  async function load() { try { const response=await adminListLoanManagers(); setManagers(response.managers); } catch(e:any) { setError(e?.message||"Unable to load loan managers."); } }
  useEffect(()=>{void load();},[]);
  async function create() {
    setMessage(""); setError(""); if(!email.trim()||!name.trim()||!phone.trim()||password.length<12){setError("Enter name, email, phone, and a password of at least 12 characters.");return;}
    setBusy(true); try { await adminCreateLoanManager(email.trim(),name.trim(),window.location.origin,phone.trim(),password); setMessage("Loan manager created with the LOAN_MANAGER role."); setName(""); setEmail(""); setPhone(""); setPassword(""); await load(); } catch(e:any){setError(e?.message||"Unable to create account.");} finally{setBusy(false);}
  }
  return <div className="max-w-3xl space-y-5"><div className="velo-card p-5 space-y-4"><div><h2 className="text-lg font-bold text-velo-900">Loan Manager Accounts</h2><p className="text-sm text-slate-500 mt-1">New accounts automatically receive the LOAN_MANAGER role.</p></div><input className="velo-input" placeholder="Manager name" value={name} onChange={e=>setName(e.target.value)}/><input className="velo-input" type="email" placeholder="Manager email" value={email} onChange={e=>setEmail(e.target.value)}/><input className="velo-input" placeholder="Nigerian phone number" value={phone} onChange={e=>setPhone(e.target.value)}/><input className="velo-input" type="password" placeholder="Temporary password (12+ characters)" value={password} onChange={e=>setPassword(e.target.value)}/>{message&&<div className="rounded-lg bg-emerald-50 border border-emerald-100 p-3 text-sm text-emerald-700">{message}</div>}{error&&<div className="rounded-lg bg-red-50 border border-red-100 p-3 text-sm text-red-700">{error}</div>}<button type="button" className="btn-primary" disabled={busy} onClick={create}>{busy?"Creating…":"Create Loan Manager"}</button></div><div className="velo-card divide-y divide-slate-100">{managers.map(manager=><div className="flex flex-wrap items-center justify-between gap-3 p-4" key={manager.id}><div><div className="font-semibold text-velo-900">{manager.fullName}</div><div className="text-xs text-slate-500">{manager.email} · {manager.phone}</div><span className={`badge ${manager.isActive===false?"badge-pending":"badge-completed"}`}>{manager.isActive===false?"DEACTIVATED":"ACTIVE"}</span></div><div className="flex gap-2"><button className="btn-ghost text-xs" onClick={async()=>{await adminSetLoanManagerStatus(manager.id,manager.isActive===false);await load();}}>{manager.isActive===false?"Activate":"Deactivate"}</button><button className="btn-ghost text-xs text-red-600" onClick={async()=>{if(window.confirm("Delete this loan manager?")){await adminDeleteLoanManager(manager.id);await load();}}}>Delete</button></div></div>)}{managers.length===0&&<p className="p-5 text-sm text-slate-500">No loan managers found.</p>}</div></div>;
}
