import { useEffect, useState } from "react";
import { ADMIN_PERMISSIONS, adminCreateLoanManager, adminDeleteLoanManager, adminListLoanManagers, adminSetLoanManagerStatus, type AdminPermission, type LoanManager } from "../../services/adminApi";

export default function LoanManagerAdmin() {
  const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [phone, setPhone] = useState(""); const [password, setPassword] = useState("");
  const [permissions, setPermissions] = useState<AdminPermission[]>([...ADMIN_PERMISSIONS]); const [managers, setManagers] = useState<LoanManager[]>([]); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  async function load() { try { setManagers((await adminListLoanManagers()).managers); } catch (err) { setError(err instanceof Error ? err.message : "Unable to load loan managers"); } }
  useEffect(() => { void load(); }, []);
  async function create() {
    setMessage(""); setError(""); if (!email.trim() || !name.trim() || !phone.trim() || password.length < 12) { setError("Enter name, email, phone, and a password of at least 12 characters."); return; }
    setBusy(true); try { await adminCreateLoanManager(email.trim(), name.trim(), window.location.origin, phone.trim(), password, permissions); setMessage("Loan manager created with the selected permissions."); setName(""); setEmail(""); setPhone(""); setPassword(""); await load(); } catch (err) { setError(err instanceof Error ? err.message : "Unable to create account"); } finally { setBusy(false); }
  }
  return <div className="max-w-3xl space-y-5">
    <div className="velo-card space-y-4 p-5"><div><h2 className="text-lg font-bold text-velo-900">Loan Manager Accounts</h2><p className="mt-1 text-sm text-slate-500">Select the back-office areas this manager can access.</p></div>
      <input className="velo-input" placeholder="Manager name" value={name} onChange={(event) => setName(event.target.value)} /><input className="velo-input" type="email" placeholder="Manager email" value={email} onChange={(event) => setEmail(event.target.value)} /><input className="velo-input" placeholder="Nigerian phone number" value={phone} onChange={(event) => setPhone(event.target.value)} /><input className="velo-input" type="password" placeholder="Temporary password (12+ characters)" value={password} onChange={(event) => setPassword(event.target.value)} />
      <div><p className="velo-label">Permissions</p><div className="mt-2 grid gap-2 sm:grid-cols-3">{ADMIN_PERMISSIONS.map((permission) => <label key={permission} className="flex items-center gap-2 text-xs"><input type="checkbox" checked={permissions.includes(permission)} onChange={() => setPermissions((current) => current.includes(permission) ? current.filter((item) => item !== permission) : [...current, permission])} />{permission}</label>)}</div></div>
      {message && <div className="rounded-lg border border-emerald-100 bg-emerald-50 p-3 text-sm text-emerald-700">{message}</div>}{error && <div className="rounded-lg border border-red-100 bg-red-50 p-3 text-sm text-red-700">{error}</div>}<button type="button" className="btn-primary" disabled={busy} onClick={create}>{busy ? "Creating…" : "Create Loan Manager"}</button>
    </div>
    <div className="velo-card divide-y divide-slate-100">{managers.map((manager) => <div className="flex flex-wrap items-center justify-between gap-3 p-4" key={manager.id}><div><div className="font-semibold text-velo-900">{manager.fullName}</div><div className="text-xs text-slate-500">{manager.email} · {manager.phone}</div><div className="mt-1 text-xs text-slate-500">{(manager.adminPermissions ?? []).join(", ") || "No permissions"}</div><span className={`badge ${manager.isActive === false ? "badge-pending" : "badge-completed"}`}>{manager.isActive === false ? "DEACTIVATED" : "ACTIVE"}</span></div><div className="flex gap-2"><button className="btn-ghost text-xs" onClick={async () => { await adminSetLoanManagerStatus(manager.id, manager.isActive === false); await load(); }}>{manager.isActive === false ? "Activate" : "Deactivate"}</button><button className="btn-ghost text-xs text-red-600" onClick={async () => { if (window.confirm("Delete this loan manager?")) { await adminDeleteLoanManager(manager.id); await load(); } }}>Delete</button></div></div>)}</div>
  </div>;
}
