import type { ApplicationData, DraftIndexEntry } from "../types/application";
const APP_PREFIX="velo:applications:";const INDEX_KEY="velo:draft-index";const PROGRESS_PREFIX="velo:application-progress:";const DRAFT_TTL_MS=24*60*60*1000;
export function loadApplication(id:string):ApplicationData|null{if(!id)return null;try{const raw=localStorage.getItem(APP_PREFIX+id);if(!raw)return null;const app=JSON.parse(raw) as ApplicationData;if((app.status==="DRAFT"||app.status==="IN_PROGRESS")&&app.updatedAt){const updated=new Date(app.updatedAt).getTime();if(Number.isFinite(updated)&&Date.now()-updated>DRAFT_TTL_MS){deleteApplication(id);return null;}}return app;}catch(e){console.warn("[storage] Failed to load application",id,e);return null;}}
export function saveApplication(data:ApplicationData,sectionIndex=0):void{if(!data?.applicationId)return;try{localStorage.setItem(APP_PREFIX+data.applicationId,JSON.stringify(data));localStorage.setItem(PROGRESS_PREFIX+data.applicationId,String(sectionIndex));upsertIndex(data);}catch(e){console.warn("[storage] Failed to save application",data.applicationId,e);}}
export function getSavedSectionIndex(data:ApplicationData):number{const saved=Number(localStorage.getItem(PROGRESS_PREFIX+data.applicationId));return Number.isFinite(saved)&&saved>=0?saved:0;}
export function deleteApplication(id:string):void{if(!id)return;try{localStorage.removeItem(APP_PREFIX+id);localStorage.removeItem(PROGRESS_PREFIX+id);removeFromIndex(id);}catch(e){console.warn("[storage] Failed to delete application",id,e);}}
export function loadIndex():DraftIndexEntry[]{try{const raw=localStorage.getItem(INDEX_KEY);if(!raw)return[];const arr=JSON.parse(raw) as DraftIndexEntry[];if(!Array.isArray(arr))return[];const cutoff=Date.now()-DRAFT_TTL_MS;const valid=arr.filter(e=>{if(e.status!=="DRAFT"&&e.status!=="IN_PROGRESS")return true;const updated=new Date(e.updatedAt||e.createdAt||"").getTime();if(!Number.isFinite(updated)||updated>=cutoff)return true;localStorage.removeItem(APP_PREFIX+e.applicationId);localStorage.removeItem(PROGRESS_PREFIX+e.applicationId);return false;});if(valid.length!==arr.length)saveIndex(valid);return valid;}catch{return[];}}
function saveIndex(entries:DraftIndexEntry[]):void{try{localStorage.setItem(INDEX_KEY,JSON.stringify(entries));}catch(e){console.warn("[storage] Failed to save draft index",e);}}
export function upsertIndex(data:ApplicationData):void{const entries=loadIndex();const applicantType=data.applicantType;const email=data.applicantType==="PERSONAL"?data.personalInfo.email:data.businessRep.email;const phone=data.applicantType==="PERSONAL"?data.personalInfo.phone:data.businessRep.phone;const displayName=data.applicantType==="PERSONAL"?data.personalInfo.fullName:data.businessInfo.businessName;if(!email&&!phone)return;const idx=entries.findIndex(e=>e.applicationId===data.applicationId);const entry:DraftIndexEntry={applicationId:data.applicationId,applicantType:applicantType as DraftIndexEntry["applicantType"],email,phone,createdAt:data.createdAt,updatedAt:data.updatedAt,status:data.status,displayName};if(idx>=0)entries[idx]=entry;else entries.push(entry);saveIndex(entries);}
function removeFromIndex(id:string):void{saveIndex(loadIndex().filter(e=>e.applicationId!==id));}
export function findDraftsByEmailOrPhone(email:string,phone:string):DraftIndexEntry[]{if(!email&&!phone)return[];const e=email.trim().toLowerCase(),p=phone.trim();return loadIndex().filter(entry=>(e&&entry.email&&entry.email.toLowerCase()===e)||(p&&entry.phone&&entry.phone.replace(/[\s-]/g,"")===p.replace(/[\s-]/g,"")));}
