import { env } from "./config.js";

function escapeHtml(value: unknown): string { return String(value ?? "").replace(/[&<>"']/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[character] ?? character); }
export type ReminderKind = "SEVEN_DAYS" | "THREE_DAYS" | "DUE_TODAY" | "OVERDUE";

export function loanReminderEmail(input: { borrowerName: string; amountNaira: number; dueDate: string; outstandingNaira: number; lateFee: string; kind: ReminderKind }): { subject: string; html: string } {
  const titles: Record<ReminderKind, string> = { SEVEN_DAYS: "Your Velo repayment is due in 7 days", THREE_DAYS: "Your Velo repayment is due in 3 days", DUE_TODAY: "Your Velo repayment is due today", OVERDUE: "Your Velo repayment is overdue" };
  const accent = input.kind === "OVERDUE" ? "#dc2626" : "#2196f3";
  const logo = env.BRAND_LOGO_URL ? `<img src="${escapeHtml(env.BRAND_LOGO_URL)}" alt="Velo Finance" style="height:42px;width:auto" />` : `<strong style="font-size:24px;color:#17243d">VELO</strong>`;
  return { subject: titles[input.kind], html: `<!doctype html><html><body style="margin:0;background:#f4f8fc;font-family:Arial,sans-serif;color:#17243d"><div style="max-width:600px;margin:32px auto;background:#fff;border-radius:18px;overflow:hidden;box-shadow:0 8px 28px rgba(15,35,65,.08)"><div style="padding:26px 30px;border-bottom:1px solid #e5edf5">${logo}</div><div style="padding:30px"><div style="display:inline-block;padding:7px 11px;border-radius:999px;background:${accent}18;color:${accent};font-size:12px;font-weight:700">${escapeHtml(input.kind === "OVERDUE" ? "ACTION REQUIRED" : "REPAYMENT REMINDER")}</div><h1 style="font-size:25px;line-height:1.2;margin:18px 0 10px">${escapeHtml(titles[input.kind])}</h1><p style="font-size:15px;line-height:1.6;color:#526173">Hello ${escapeHtml(input.borrowerName)}, here is an update about your Velo loan repayment.</p><div style="margin:24px 0;padding:18px;background:#f7fafc;border:1px solid #e5edf5;border-radius:12px"><p style="margin:0 0 10px;color:#526173;font-size:13px">Outstanding balance</p><strong style="font-size:25px">₦${escapeHtml(input.outstandingNaira.toLocaleString("en-NG"))}</strong><p style="margin:14px 0 0;color:#526173;font-size:13px">Due date: <strong>${escapeHtml(input.dueDate)}</strong></p>${input.kind === "OVERDUE" ? `<p style="margin:8px 0 0;color:#b91c1c;font-size:13px">Late terms: ${escapeHtml(input.lateFee)}</p>` : ""}</div><p style="font-size:14px;line-height:1.6;color:#526173">Please sign in to your Velo dashboard to review your repayment schedule and use the available Flutterwave payment methods.</p><p style="font-size:13px;line-height:1.6;color:#718096">If you have already paid, please allow time for provider confirmation. Do not make a duplicate payment while your transaction is pending.</p></div><div style="padding:20px 30px;background:#17243d;color:#d7e7f5;font-size:12px;line-height:1.5">Velo Finance LTD · Nigeria<br/>This is an automated account notification. Please contact support if you need help.</div></div></body></html>` };
}

function brandedEmailHtml(content: string): string {
  const body = content.match(/<body[^>]*>([\s\S]*)<\/body>/i)?.[1] ?? content;
  const logo = env.BRAND_LOGO_URL
    ? `<img src="${escapeHtml(env.BRAND_LOGO_URL)}" alt="Velo Finance" style="display:block;height:42px;width:auto;max-width:190px" />`
    : `<div style="font-size:24px;font-weight:800;letter-spacing:.08em;color:#17243d">VELO</div>`;
  return `<!doctype html><html><head><meta name="color-scheme" content="light" /><meta name="supported-color-schemes" content="light" /></head><body style="margin:0;background:#eef5fb;font-family:Arial,Helvetica,sans-serif;color:#17243d"><div style="padding:28px 12px"><div style="max-width:620px;margin:0 auto;background:#ffffff;border:1px solid #dce8f3;border-radius:22px;overflow:hidden;box-shadow:0 16px 42px rgba(15,35,65,.10)"><div style="padding:24px 30px;background:linear-gradient(135deg,#17243d,#14548b);border-bottom:4px solid #2196f3">${logo}</div><div style="padding:30px">${body}</div><div style="padding:22px 30px;background:#f5f9fd;border-top:1px solid #e3edf6;color:#60748a;font-size:12px;line-height:1.7">Velo Finance LTD · Nigeria<br/>This is an automated message from Velo Finance. Please do not share OTPs or account credentials.<br/><span style="color:#2196f3;font-weight:700">Finance that moves with you.</span></div></div></div></body></html>`;
}

export function welcomeEmail(input: { name: string }): { subject: string; html: string } {
  return { subject: "Welcome to Velo Finance", html: `<div><div style="display:inline-block;padding:7px 11px;border-radius:999px;background:#2196f318;color:#1d4ed8;font-size:12px;font-weight:700">WELCOME TO VELO</div><h1 style="font-size:26px;margin:18px 0 10px">Welcome, ${escapeHtml(input.name)}</h1><p style="font-size:15px;line-height:1.7;color:#526173">Your Velo Finance account is ready. Complete your verification to unlock your investor and borrower features.</p><div style="margin:24px 0;padding:18px;border:1px solid #dce8f3;border-radius:14px;background:#f7fafc"><strong style="font-size:16px">Finance that moves with you.</strong><p style="margin:8px 0 0;color:#526173;font-size:13px;line-height:1.6">You can use the same account to invest, apply for loans, and track your financial activity securely.</p></div><p style="font-size:14px;line-height:1.7;color:#526173">If you did not create this account, please contact support immediately.</p></div>` };
}

export function loginAttemptEmail(input: { name: string; device: string; ipAddress: string; attemptedAt: string }): { subject: string; html: string } {
  return { subject: "New login to your Velo account", html: `<div><div style="display:inline-block;padding:7px 11px;border-radius:999px;background:#f59e0b18;color:#b45309;font-size:12px;font-weight:700">LOGIN ALERT</div><h1 style="font-size:25px;margin:18px 0 10px">A login was detected</h1><p style="font-size:15px;line-height:1.7;color:#526173">Hello ${escapeHtml(input.name)}, your Velo account was accessed successfully.</p><div style="margin:24px 0;padding:18px;border:1px solid #dce8f3;border-radius:14px;background:#f7fafc"><p style="margin:0 0 8px;color:#526173;font-size:13px">Device</p><strong>${escapeHtml(input.device)}</strong><p style="margin:14px 0 8px;color:#526173;font-size:13px">IP address</p><strong>${escapeHtml(input.ipAddress)}</strong><p style="margin:14px 0 0;color:#526173;font-size:13px">Time</p><strong>${escapeHtml(input.attemptedAt)}</strong></div><p style="font-size:14px;line-height:1.7;color:#526173">If this was not you, reset your password and contact support.</p></div>` };
}

export function kycStatusEmail(input: { name: string; status: "APPROVED" | "REJECTED"; category?: string; reason?: string }): { subject: string; html: string } {
  const approved = input.status === "APPROVED";
  return { subject: `Your Velo KYC was ${approved ? "approved" : "rejected"}`, html: `<div><div style="display:inline-block;padding:7px 11px;border-radius:999px;background:${approved ? "#10b98118;color:#059669" : "#dc262618;color:#b91c1c"};font-size:12px;font-weight:700">KYC ${input.status}</div><h1 style="font-size:25px;margin:18px 0 10px">${approved ? "Verification approved" : "Action needed on your verification"}</h1><p style="font-size:15px;line-height:1.7;color:#526173">Hello ${escapeHtml(input.name)}, your ${escapeHtml(input.category || "KYC")} status has been updated.</p>${input.reason ? `<div style="margin:24px 0;padding:18px;border:1px solid #fecaca;border-radius:14px;background:#fff7f7"><p style="margin:0 0 7px;color:#b91c1c;font-size:13px;font-weight:700">Reason for rejection</p><p style="margin:0;color:#526173;font-size:14px;line-height:1.6">${escapeHtml(input.reason)}</p></div>` : ""}<p style="font-size:14px;line-height:1.7;color:#526173">Sign in to your dashboard to review the status of each verification requirement.</p></div>` };
}

export function kycSubmittedEmail(input: { name: string; source?: "LOAN_APPLICATION" | "KYC_PAGE" }): { subject: string; html: string } {
  const viaLoan = input.source === "LOAN_APPLICATION";
  return { subject: "Your Velo identity verification was submitted", html: `<div><div style="display:inline-block;padding:7px 11px;border-radius:999px;background:#2196f318;color:#1d4ed8;font-size:12px;font-weight:700">KYC UNDER REVIEW</div><h1 style="font-size:25px;margin:18px 0 10px">Verification submitted</h1><p style="font-size:15px;line-height:1.7;color:#526173">Hello ${escapeHtml(input.name)}, your identity verification has been submitted${viaLoan ? " using the details from your loan application" : ""} and is now being reviewed by our team.</p><div style="margin:24px 0;padding:18px;border:1px solid #dce8f3;border-radius:14px;background:#f7fafc"><p style="margin:0;color:#526173;font-size:14px;line-height:1.7">What happens next:<br/>1. Our team reviews your verification details (usually within 24–48 hours).<br/>2. You get an email the moment your KYC is approved.<br/>3. Approved verification unlocks loans, investing and payouts.</p></div><p style="font-size:14px;line-height:1.7;color:#526173">No further action is needed from you right now.</p></div>` };
}

export function kycActionBlockedEmail(input: { name: string; action: "LOAN_DISBURSEMENT" | "INVESTMENT" | "INVESTOR_PAYOUT" | "WITHDRAWAL" | "EARLY_LIQUIDITY" }): { subject: string; html: string } {
  const actionLabels: Record<string, string> = {
    LOAN_DISBURSEMENT: "receive your loan disbursement",
    INVESTMENT: "start a new investment",
    INVESTOR_PAYOUT: "receive your investment payout",
    WITHDRAWAL: "withdraw from your wallet",
    EARLY_LIQUIDITY: "request early liquidity",
  };
  const label = actionLabels[input.action] ?? "continue this action";
  return { subject: "Action needed: verify your identity to continue", html: `<div><div style="display:inline-block;padding:7px 11px;border-radius:999px;background:#f59e0b18;color:#b45309;font-size:12px;font-weight:700">KYC PENDING</div><h1 style="font-size:25px;margin:18px 0 10px">Your identity verification is pending</h1><p style="font-size:15px;line-height:1.7;color:#526173">Hello ${escapeHtml(input.name)}, we received a request to ${escapeHtml(label)}, but your KYC verification is not completed yet.</p><div style="margin:24px 0;padding:18px;border:1px solid #fde68a;border-radius:14px;background:#fffbeb"><p style="margin:0 0 7px;color:#b45309;font-size:13px;font-weight:700">How to unlock this action</p><p style="margin:0;color:#526173;font-size:14px;line-height:1.7">Sign in to your Velo dashboard, open the <strong>Verification</strong> page and complete your KYC. Your details from previous applications are already pre-filled — most customers only need to confirm and submit.</p></div><p style="font-size:14px;line-height:1.7;color:#526173">As soon as your KYC is approved, retry the action and it will go through.</p></div>` };
}

export function maintenanceModeEmail(input: { name: string; isOn: boolean; message?: string }): { subject: string; html: string } {
  const on = input.isOn;
  return { subject: on ? "Velo is temporarily under maintenance" : "Velo is back online", html: `<div><div style="display:inline-block;padding:7px 11px;border-radius:999px;background:${on ? "#f59e0b18;color:#b45309" : "#10b98118;color:#059669"};font-size:12px;font-weight:700">${on ? "SCHEDULED MAINTENANCE" : "SYSTEM BACK ONLINE"}</div><h1 style="font-size:25px;margin:18px 0 10px">${on ? "We're improving Velo for you" : "Velo is up and running again"}</h1><p style="font-size:15px;line-height:1.7;color:#526173">Hello ${escapeHtml(input.name)}, ${on ? "Velo is currently undergoing scheduled maintenance. During this time you may be unable to sign in or use the platform." : "the maintenance break is over — every feature is available again."}</p>${on && input.message ? `<div style="margin:24px 0;padding:18px;border:1px solid #fde68a;border-radius:14px;background:#fffbeb"><p style="margin:0;color:#526173;font-size:14px;line-height:1.7">${escapeHtml(input.message)}</p></div>` : ""}<p style="font-size:14px;line-height:1.7;color:#526173">${on ? "You will receive an email from us the moment the system is back up. Your data and pending transactions are safe." : "Thank you for your patience while we made Velo better."}</p></div>` };
}

export function loanApplicationSubmittedEmail(input: { name: string; applicationId: string; amountNaira: number; recipient: "borrower" | "reviewer" }): { subject: string; html: string } {
  const reviewer = input.recipient === "reviewer";
  return { subject: reviewer ? `Loan application ${input.applicationId} requires review` : "Your Velo loan application was submitted", html: `<div><div style="display:inline-block;padding:7px 11px;border-radius:999px;background:#2196f318;color:#1d4ed8;font-size:12px;font-weight:700">LOAN SUBMITTED</div><h1 style="font-size:25px;margin:18px 0 10px">${reviewer ? "New loan application received" : "Application received"}</h1><p style="font-size:15px;line-height:1.7;color:#526173">Hello ${escapeHtml(input.name)}, ${reviewer ? "a borrower has submitted a loan application for your review." : "we have received your loan application and it is now under review."}</p><div style="margin:24px 0;padding:18px;border:1px solid #dce8f3;border-radius:14px;background:#f7fafc"><p style="margin:0 0 7px;color:#526173;font-size:13px">Application reference</p><strong>${escapeHtml(input.applicationId)}</strong><p style="margin:14px 0 0;color:#526173;font-size:13px">Requested amount: <strong>₦${escapeHtml(input.amountNaira.toLocaleString("en-NG"))}</strong></p></div><p style="font-size:14px;line-height:1.7;color:#526173">${reviewer ? "Please review and update the application within 24–48 hours." : "You can track the status from your borrower dashboard. We will email you when a decision is made."}</p></div>` };
}

export function loanDecisionEmail(input: { name: string; applicationId: string; status: "APPROVED" | "REJECTED"; amountNaira: number; note?: string }): { subject: string; html: string } {
  const approved = input.status === "APPROVED";
  return { subject: `Your Velo loan application was ${approved ? "approved" : "rejected"}`, html: `<div><div style="display:inline-block;padding:7px 11px;border-radius:999px;background:${approved ? "#10b98118;color:#059669" : "#dc262618;color:#b91c1c"};font-size:12px;font-weight:700">LOAN ${input.status}</div><h1 style="font-size:25px;margin:18px 0 10px">Loan application ${approved ? "approved" : "not approved"}</h1><p style="font-size:15px;line-height:1.7;color:#526173">Hello ${escapeHtml(input.name)}, your loan application <strong>${escapeHtml(input.applicationId)}</strong> for <strong>₦${escapeHtml(input.amountNaira.toLocaleString("en-NG"))}</strong> has been ${approved ? "approved and is awaiting disbursement" : "rejected"}.</p>${input.note ? `<div style="margin:24px 0;padding:18px;border:1px solid ${approved ? "#bbf7d0" : "#fecaca"};border-radius:14px;background:${approved ? "#f0fdf4" : "#fff7f7"}"><p style="margin:0 0 7px;color:#526173;font-size:13px">Review note</p><p style="margin:0;color:#526173;font-size:14px;line-height:1.6">${escapeHtml(input.note)}</p></div>` : ""}<p style="font-size:14px;line-height:1.7;color:#526173">Sign in to your dashboard to view the latest status.</p></div>` };
}

export function loanAwaitingDisbursementEmail(input: { name: string; applicationId: string; amountNaira: number }): { subject: string; html: string } {
  return { subject: `Loan ${input.applicationId} is awaiting disbursement`, html: `<div><div style="display:inline-block;padding:7px 11px;border-radius:999px;background:#f59e0b18;color:#b45309;font-size:12px;font-weight:700">DISBURSEMENT REQUIRED</div><h1 style="font-size:25px;margin:18px 0 10px">Approved loan awaiting disbursement</h1><p style="font-size:15px;line-height:1.7;color:#526173">Hello ${escapeHtml(input.name)}, loan application <strong>${escapeHtml(input.applicationId)}</strong> for <strong>₦${escapeHtml(input.amountNaira.toLocaleString("en-NG"))}</strong> has been approved and is ready for transfer.</p><p style="font-size:14px;line-height:1.7;color:#526173">Sign in to the admin workspace to review the verified account and initiate disbursement through Flutterwave.</p></div>` };
}

export function loanDisbursedEmail(input: { name: string; applicationId: string; amountNaira: number }): { subject: string; html: string } {
  return { subject: "Your Velo loan has been disbursed", html: `<div><div style="display:inline-block;padding:7px 11px;border-radius:999px;background:#10b98118;color:#059669;font-size:12px;font-weight:700">LOAN DISBURSED</div><h1 style="font-size:25px;margin:18px 0 10px">Your funds are on the way</h1><p style="font-size:15px;line-height:1.7;color:#526173">Hello ${escapeHtml(input.name)}, your loan application <strong>${escapeHtml(input.applicationId)}</strong> has been successfully disbursed to your verified bank account.</p><div style="margin:24px 0;padding:18px;border:1px solid #dce8f3;border-radius:14px;background:#f7fafc"><p style="margin:0 0 7px;color:#526173;font-size:13px">Disbursed amount</p><strong style="font-size:24px">₦${escapeHtml(input.amountNaira.toLocaleString("en-NG"))}</strong></div><p style="font-size:14px;line-height:1.7;color:#526173">Your repayment schedule is available in your borrower dashboard.</p></div>` };
}

export function loanRepaymentEmail(input: { name: string; loanId: string; amountNaira: number; outstandingNaira: number; fullyRepaid: boolean }): { subject: string; html: string } {
  const title = input.fullyRepaid ? "Your Velo loan is fully repaid" : "Your Velo loan repayment was confirmed";
  const badge = input.fullyRepaid ? "LOAN REPAID" : "REPAYMENT CONFIRMED";
  return { subject: title, html: `<div><div style="display:inline-block;padding:7px 11px;border-radius:999px;background:#10b98118;color:#059669;font-size:12px;font-weight:700">${badge}</div><h1 style="font-size:25px;margin:18px 0 10px">${title}</h1><p style="font-size:15px;line-height:1.7;color:#526173">Hello ${escapeHtml(input.name)}, your repayment of <strong>₦${escapeHtml(input.amountNaira.toLocaleString("en-NG"))}</strong> for loan <strong>${escapeHtml(input.loanId)}</strong> has been confirmed.</p><div style="margin:24px 0;padding:18px;border:1px solid #dce8f3;border-radius:14px;background:#f7fafc"><p style="margin:0 0 7px;color:#526173;font-size:13px">${input.fullyRepaid ? "Loan balance" : "Remaining balance"}</p><strong style="font-size:24px;color:#059669">₦${escapeHtml(input.outstandingNaira.toLocaleString("en-NG"))}</strong></div><p style="font-size:14px;line-height:1.7;color:#526173">Sign in to your borrower dashboard to view your repayment history.</p></div>` };
}

export function loanRepaymentAdminEmail(input: { name: string; borrowerName: string; loanId: string; amountNaira: number; outstandingNaira: number; fullyRepaid: boolean }): { subject: string; html: string } {
  return { subject: `${input.fullyRepaid ? "Loan fully repaid" : "Loan repayment received"} — ${input.loanId}`, html: `<div><div style="display:inline-block;padding:7px 11px;border-radius:999px;background:#2196f318;color:#1d4ed8;font-size:12px;font-weight:700">LOAN REPAYMENT</div><h1 style="font-size:25px;margin:18px 0 10px">${input.fullyRepaid ? "Loan fully repaid" : "Repayment received"}</h1><p style="font-size:15px;line-height:1.7;color:#526173">Hello ${escapeHtml(input.name)}, ${escapeHtml(input.borrowerName)} made a repayment of <strong>₦${escapeHtml(input.amountNaira.toLocaleString("en-NG"))}</strong> on loan <strong>${escapeHtml(input.loanId)}</strong>.</p><p style="font-size:14px;line-height:1.7;color:#526173">Remaining balance: <strong>₦${escapeHtml(input.outstandingNaira.toLocaleString("en-NG"))}</strong></p></div>` };
}

export function disbursementAccountUpdateRequestedEmail(input: { name: string; applicationId: string; amountNaira: number; note?: string }): { subject: string; html: string } {
  return { subject: "Urgent: update your disbursement account to receive your loan", html: `<div><div style="display:inline-block;padding:7px 11px;border-radius:999px;background:#dc262618;color:#b91c1c;font-size:12px;font-weight:700">URGENT ACTION NEEDED</div><h1 style="font-size:25px;margin:18px 0 10px">Your loan disbursement needs your attention</h1><p style="font-size:15px;line-height:1.7;color:#526173">Hello ${escapeHtml(input.name)}, your approved loan <strong>${escapeHtml(input.applicationId)}</strong> for <strong>₦${escapeHtml(input.amountNaira.toLocaleString("en-NG"))}</strong> could not be paid out because the bank account saved on your profile could not be verified by our payment provider.</p><div style="margin:24px 0;padding:18px;border:1px solid #fecaca;border-radius:14px;background:#fff7f7"><p style="margin:0 0 7px;color:#b91c1c;font-size:13px;font-weight:700">What you need to do</p><p style="margin:0;color:#526173;font-size:14px;line-height:1.7">Sign in to your Velo dashboard, open <strong>Disbursement</strong> in the menu, and update your bank account details with a valid account that can receive transfers. Your loan will be disbursed as soon as the new account is confirmed.</p></div>${input.note ? `<div style="margin:0 0 24px;padding:14px 18px;border:1px solid #dce8f3;border-radius:14px;background:#f7fafc"><p style="margin:0;color:#526173;font-size:13px;line-height:1.6">Note from the Velo team: ${escapeHtml(input.note)}</p></div>` : ""}<p style="font-size:14px;line-height:1.7;color:#526173">No funds are lost — the loan is simply waiting for a valid account to be paid into.</p></div>` };
}

export async function sendEmail(input: { to: string; name: string; subject: string; html: string }): Promise<{ sent: boolean; providerReference?: string }> {
  if (!env.BREVO_API_KEY || !env.BREVO_SENDER_EMAIL) return { sent: false };
  const response = await fetch(`${env.BREVO_API_URL}/smtp/email`, { method: "POST", headers: { "api-key": env.BREVO_API_KEY, "Content-Type": "application/json" }, body: JSON.stringify({ sender: { email: env.BREVO_SENDER_EMAIL, name: env.BREVO_SENDER_NAME }, to: [{ email: input.to, name: input.name }], subject: input.subject, htmlContent: brandedEmailHtml(input.html) }) });
  const data = await response.json() as { messageId?: string; message?: string };
  if (!response.ok) throw new Error(data.message || `Email provider failed (${response.status})`);
  return { sent: true, providerReference: data.messageId };
}

export function investorWalletFundedEmail(input: { investorName: string; amountNaira: number; balanceNaira: number; reference: string }): { subject: string; html: string } {
  return {
    subject: "Your Velo wallet has been funded",
    html: `<div style="font-family:Arial,sans-serif;color:#17243d"><div style="display:inline-block;padding:7px 11px;border-radius:999px;background:#10b98118;color:#059669;font-size:12px;font-weight:700">WALLET FUNDED</div><h1 style="font-size:25px;line-height:1.2;margin:18px 0 10px">Wallet credited successfully</h1><p style="font-size:15px;line-height:1.6;color:#526173">Hello ${escapeHtml(input.investorName)}, your investor wallet has been credited.</p><div style="margin:24px 0;padding:18px;background:#f7fafc;border:1px solid #e5edf5;border-radius:12px"><div style="margin-bottom:14px"><p style="margin:0 0 6px;color:#526173;font-size:13px">Amount credited</p><strong style="font-size:28px;color:#059669">₦${escapeHtml(input.amountNaira.toLocaleString("en-NG"))}</strong></div><div style="display:grid;grid-template-columns:1fr 1fr;gap:12px;padding-top:14px;border-top:1px solid #e5edf5"><div><p style="margin:0 0 4px;color:#526173;font-size:12px">Current balance</p><strong style="font-size:16px">₦${escapeHtml(input.balanceNaira.toLocaleString("en-NG"))}</strong></div><div><p style="margin:0 0 4px;color:#526173;font-size:12px">Reference</p><code style="font-size:12px;background:#edf2f7;padding:4px 8px;border-radius:6px">${escapeHtml(input.reference)}</code></div></div></div><p style="font-size:14px;line-height:1.6;color:#526173">You can now invest your funds in any of our available investment plans. Sign in to review your dashboard.</p></div>`,
  };
}

export function investorEarningsCreditedEmail(input: { investorName: string; investmentId: string; principalNaira: number; earningsNaira: number; totalNaira: number; balanceNaira: number }): { subject: string; html: string } {
  return {
    subject: "Investment earnings credited to your wallet",
    html: `<div style="font-family:Arial,sans-serif;color:#17243d"><div style="display:inline-block;padding:7px 11px;border-radius:999px;background:#2196f318;color:#1d4ed8;font-size:12px;font-weight:700">INVESTMENT RETURN</div><h1 style="font-size:25px;line-height:1.2;margin:18px 0 10px">Investment payout — ${escapeHtml(input.investmentId.slice(0, 8).toUpperCase())}</h1><p style="font-size:15px;line-height:1.6;color:#526173">Hello ${escapeHtml(input.investorName)}, your investment has matured and the return has been credited to your wallet.</p><div style="margin:24px 0;padding:18px;background:#f7fafc;border:1px solid #e5edf5;border-radius:12px"><div style="display:grid;grid-template-columns:1fr 1fr;gap:14px"><div><p style="margin:0 0 6px;color:#526173;font-size:13px">Principal</p><strong style="font-size:18px">₦${escapeHtml(input.principalNaira.toLocaleString("en-NG"))}</strong></div><div><p style="margin:0 0 6px;color:#059669;font-size:13px">Earnings</p><strong style="font-size:18px;color:#059669">₦${escapeHtml(input.earningsNaira.toLocaleString("en-NG"))}</strong></div></div><div style="margin-top:14px;padding-top:14px;border-top:1px solid #e5edf5"><div style="display:grid;grid-template-columns:1fr 1fr;gap:12px"><div><p style="margin:0 0 6px;color:#526173;font-size:13px">Total credited</p><strong style="font-size:22px;color:#1d4ed8">₦${escapeHtml(input.totalNaira.toLocaleString("en-NG"))}</strong></div><div><p style="margin:0 0 6px;color:#526173;font-size:13px">Wallet balance</p><strong style="font-size:18px">₦${escapeHtml(input.balanceNaira.toLocaleString("en-NG"))}</strong></div></div></div></div><p style="font-size:14px;line-height:1.6;color:#526173">Your funds are now available for reinvestment or withdrawal. Sign in to view your investment history.</p></div>`,
  };
}

export function investorWithdrawalEmail(input: { investorName: string; withdrawalId: string; amountNaira: number; feeNaira: number; netNaira: number; balanceNaira: number; bankName: string; accountNumber: string }): { subject: string; html: string } {
  const maskedAccount = input.accountNumber.slice(0, 2) + "****" + input.accountNumber.slice(-4);
  return {
    subject: "Withdrawal request received",
    html: `<div style="font-family:Arial,sans-serif;color:#17243d"><div style="display:inline-block;padding:7px 11px;border-radius:999px;background:#f59e0b18;color:#b45309;font-size:12px;font-weight:700">WITHDRAWAL REQUESTED</div><h1 style="font-size:25px;line-height:1.2;margin:18px 0 10px">Withdrawal — ${escapeHtml(input.withdrawalId.slice(0, 8).toUpperCase())}</h1><p style="font-size:15px;line-height:1.6;color:#526173">Hello ${escapeHtml(input.investorName)}, your withdrawal request has been received and is being processed.</p><div style="margin:24px 0;padding:18px;background:#f7fafc;border:1px solid #e5edf5;border-radius:12px"><div style="display:grid;grid-template-columns:1fr 1fr;gap:14px;margin-bottom:14px"><div><p style="margin:0 0 6px;color:#526173;font-size:13px">Gross amount</p><strong style="font-size:18px">₦${escapeHtml(input.amountNaira.toLocaleString("en-NG"))}</strong></div><div><p style="margin:0 0 6px;color:#526173;font-size:13px">Withdrawal fee</p><strong style="font-size:18px;color:#dc2626">-₦${escapeHtml(input.feeNaira.toLocaleString("en-NG"))}</strong></div></div><div style="padding-top:14px;border-top:1px solid #e5edf5"><div style="display:grid;grid-template-columns:1fr 1fr;gap:12px"><div><p style="margin:0 0 6px;color:#526173;font-size:13px">Net payout</p><strong style="font-size:22px;color:#1d4ed8">₦${escapeHtml(input.netNaira.toLocaleString("en-NG"))}</strong></div><div><p style="margin:0 0 6px;color:#526173;font-size:13px">Remaining balance</p><strong style="font-size:18px">₦${escapeHtml(input.balanceNaira.toLocaleString("en-NG"))}</strong></div></div></div></div><div style="padding:14px 16px;background:#eff6ff;border:1px solid #bfdbfe;border-radius:10px"><p style="margin:0 0 4px;color:#1d4ed8;font-size:12px;font-weight:700">Destination bank</p><p style="margin:0;font-size:14px"><strong>${escapeHtml(input.bankName)}</strong> · ${escapeHtml(maskedAccount)}</p></div><p style="font-size:14px;line-height:1.6;color:#526173;margin-top:20px">Your payout will be sent after admin approval. You'll receive a confirmation once the transfer is initiated.</p></div>`,
  };
}
