// Complete OpenAPI 3.0.3 inventory of the Velo Finance API.
// Served by the backend at /docs (Swagger UI) and /openapi.json.
// Keep in sync with backend/server/routes.ts — every route below maps to a real handler.
// All authenticated routes expect `Authorization: Bearer <JWT>`; admin routes additionally
// require the ADMIN role and are issued only through the two-step admin login.

const bearer = [{ bearerAuth: [] }];

const healthPaths = {
  "/health": { get: { tags: ["Health"], summary: "Check API and database status", responses: { "200": { description: "Healthy (or database not configured — degraded but serving)" }, "503": { description: "Database unavailable" } } } },
  "/api/v1/platform/status": { get: { tags: ["Platform"], summary: "Public platform status (maintenance mode, announcements, banners, loan products summary)", responses: { "200": { description: "Platform status consumed by the frontend at boot" } } } },
  "/api/v1/platform/banners": { get: { tags: ["Platform"], summary: "Public marketing banner carousel", responses: { "200": { description: "Active banners with image data URLs and optional links" } } } },
  "/api/v1/public/loan-products": { get: { tags: ["Platform"], summary: "PUBLIC loan product catalog (no auth) — powers the landing-page calculator with the exact admin-configured terms", parameters: [{ name: "type", in: "query", schema: { type: "string", enum: ["PERSONAL", "BUSINESS"] }, description: "Returns the SINGLE authoritative product for that flow (same resolution as the borrower endpoint)" }, { name: "productId", in: "query", schema: { type: "string" }, description: "Returns one exact ACTIVE product" }], responses: { "200": { description: "Active loan products (each carries programType PERSONAL/BUSINESS/BOTH, limits, tenors, per-tenor monthly rates and fees). Served with Cache-Control: no-store" }, "404": { description: "productId not found or inactive" } } } },
  "/openapi.json": { get: { tags: ["Health"], summary: "This OpenAPI document", responses: { "200": { description: "OpenAPI 3.0.3 JSON" } } } }
};

const authPaths = {
  "/api/v1/auth/register": { post: { tags: ["Auth"], summary: "Create an investor or borrower account", requestBody: { required: true, content: { "application/json": { schema: { type: "object", required: ["email", "phone", "fullName", "password"], properties: { email: { type: "string", format: "email" }, phone: { type: "string", example: "08012345678" }, fullName: { type: "string" }, password: { type: "string", format: "password" }, role: { type: "string", enum: ["INVESTOR", "BORROWER"] } } } } } }, responses: { "201": { description: "Account created (OTP verification may be required)" }, "400": { description: "Invalid input" }, "409": { description: "Duplicate email" } } } },
  "/api/v1/auth/register/resend-otp": { post: { tags: ["Auth"], summary: "Resend the registration OTP", responses: { "200": { description: "OTP re-sent" }, "400": { description: "Invalid or expired challenge" } } } },
  "/api/v1/auth/register/verify-otp": { post: { tags: ["Auth"], summary: "Verify registration OTP to activate the account", responses: { "200": { description: "Account verified" }, "400": { description: "Invalid code" } } } },
  "/api/v1/auth/login": { post: { tags: ["Auth"], summary: "Log in (may return an otpRequired challenge when OTP login is enforced)", requestBody: { required: true, content: { "application/json": { schema: { type: "object", required: ["email", "password"], properties: { email: { type: "string", format: "email" }, password: { type: "string", format: "password" } } } } } }, responses: { "200": { description: "JWT issued, or 200 with otpRequired + challengeId when OTP step is required" }, "401": { description: "Invalid credentials" } } } },
  "/api/v1/auth/login/resend-otp": { post: { tags: ["Auth"], summary: "Resend the login OTP", responses: { "200": { description: "OTP re-sent" } } } },
  "/api/v1/auth/login/verify-otp": { post: { tags: ["Auth"], summary: "Complete OTP login and receive the JWT", responses: { "200": { description: "JWT issued" }, "401": { description: "Invalid or expired code" } } } },
  "/api/v1/auth/admin/login": { post: { tags: ["Auth"], summary: "Step 1 of admin login — validate credentials and send an admin OTP", requestBody: { required: true, content: { "application/json": { schema: { type: "object", required: ["email", "password"], properties: { email: { type: "string", format: "email" }, password: { type: "string", format: "password" } } } } } }, responses: { "200": { description: "OTP challenge issued (challengeId returned)" }, "401": { description: "Invalid credentials" }, "403": { description: "Not an administrator" } } } },
  "/api/v1/auth/admin/login/resend-otp": { post: { tags: ["Auth"], summary: "Resend the admin login OTP", responses: { "200": { description: "OTP re-sent" } } } },
  "/api/v1/auth/admin/login/verify-otp": { post: { tags: ["Auth"], summary: "Step 2 of admin login — verify OTP and receive the admin JWT", responses: { "200": { description: "Admin JWT issued" }, "401": { description: "Invalid or expired code" } } } },
  "/api/v1/auth/admin/logout": { post: { tags: ["Auth"], security: bearer, summary: "Revoke the current admin session", responses: { "200": { description: "Session revoked" } } } },
  "/api/v1/auth/refresh": { post: { tags: ["Auth"], security: bearer, summary: "Rotate the access token", responses: { "200": { description: "New JWT issued" }, "401": { description: "Token invalid or expired" } } } },
  "/api/v1/auth/logout": { post: { tags: ["Auth"], summary: "Client-side logout (token discard)", responses: { "200": { description: "Acknowledged" } } } },
  "/api/v1/auth/otp/request": { post: { tags: ["Auth"], security: bearer, summary: "Request an OTP challenge for a sensitive action (e.g. withdrawals)", requestBody: { required: true, content: { "application/json": { schema: { type: "object", required: ["action"], properties: { action: { type: "string", example: "WITHDRAWAL" }, channel: { type: "string", enum: ["WHATSAPP", "SMS", "EMAIL"] } } } } } }, responses: { "200": { description: "Challenge created (challengeId returned)" }, "400": { description: "Invalid action or channel" } } } },
  "/api/v1/auth/otp/verify": { post: { tags: ["Auth"], summary: "Verify an OTP challenge", requestBody: { required: true, content: { "application/json": { schema: { type: "object", required: ["challengeId", "code"], properties: { challengeId: { type: "string" }, code: { type: "string", example: "123456" } } } } } }, responses: { "200": { description: "OTP verified" }, "400": { description: "Invalid or expired code" } } } },
  "/api/v1/auth/password-reset/request": { post: { tags: ["Auth"], summary: "Request a customer password reset (email delivered)", requestBody: { required: true, content: { "application/json": { schema: { type: "object", required: ["email"], properties: { email: { type: "string", format: "email" } } } } } }, responses: { "200": { description: "Reset initiated" } } } },
  "/api/v1/auth/password-reset/confirm": { post: { tags: ["Auth"], summary: "Complete a customer password reset", requestBody: { required: true, content: { "application/json": { schema: { type: "object", required: ["resetId", "token", "newPassword"], properties: { resetId: { type: "string" }, token: { type: "string" }, newPassword: { type: "string", format: "password" } } } } } }, responses: { "200": { description: "Password reset successful" }, "400": { description: "Invalid reset id or token" } } } },
  "/api/v1/auth/admin/password-reset/request": { post: { tags: ["Auth"], summary: "Request an administrator password reset", responses: { "200": { description: "Reset initiated" } } } },
  "/api/v1/auth/admin/password-reset/confirm": { post: { tags: ["Auth"], summary: "Complete an administrator password reset", responses: { "200": { description: "Password reset successful" }, "400": { description: "Invalid reset id or token" } } } }
};

const profilePaths = {
  "/api/v1/me": { get: { tags: ["Profile"], security: bearer, summary: "Current user profile, roles and KYC summary", responses: { "200": { description: "Current user" } } }, patch: { tags: ["Profile"], security: bearer, summary: "Update current user profile fields (e.g. fullName)", responses: { "200": { description: "Updated profile" }, "400": { description: "Invalid input" } } } },
  "/api/v1/me/roles/add": { post: { tags: ["Profile"], security: bearer, summary: "Add the opposite role to an existing account (become an investor as a borrower, or vice versa)", requestBody: { required: true, content: { "application/json": { schema: { type: "object", required: ["role"], properties: { role: { type: "string", enum: ["INVESTOR", "BORROWER"] } } } } } }, responses: { "200": { description: "Role added, new JWT issued" }, "409": { description: "Role already present" } } } },
  "/api/v1/user/settings": { get: { tags: ["Profile"], security: bearer, summary: "Per-user UI/notification settings", responses: { "200": { description: "User settings" } } }, put: { tags: ["Profile"], security: bearer, summary: "Replace per-user settings", responses: { "200": { description: "Settings saved" } } } },
  "/api/v1/me/profile-update/initiate": { post: { tags: ["Profile"], security: bearer, summary: "Start an OTP-verified email/phone change", requestBody: { required: true, content: { "application/json": { schema: { type: "object", properties: { email: { type: "string", format: "email" }, phone: { type: "string" } } } } } }, responses: { "200": { description: "OTP challenge issued" }, "400": { description: "No change requested or identical to current" } } } },
  "/api/v1/me/profile-update/resend-otp": { post: { tags: ["Profile"], security: bearer, summary: "Resend the profile-update OTP", responses: { "200": { description: "OTP re-sent" } } } },
  "/api/v1/me/profile-update/confirm": { post: { tags: ["Profile"], security: bearer, summary: "Confirm the profile update with the OTP code", responses: { "200": { description: "Profile updated" }, "400": { description: "Invalid code" } } } },
  "/api/v1/me/notifications": { get: { tags: ["Profile"], security: bearer, summary: "In-app notifications for the current user", responses: { "200": { description: "Notifications (newest first)" } } } },
  "/api/v1/notifications": { get: { tags: ["Profile"], security: bearer, summary: "Alias of /me/notifications", responses: { "200": { description: "Notifications" } } } },
  "/api/v1/me/consents": { get: { tags: ["Profile"], security: bearer, summary: "Consent receipts recorded for the current user", responses: { "200": { description: "Consents" } } } },
  "/api/v1/consents": { post: { tags: ["Profile"], security: bearer, summary: "Record a consent (terms, privacy, credit report, agreements…)", requestBody: { required: true, content: { "application/json": { schema: { type: "object", required: ["consentType"], properties: { consentType: { type: "string", enum: ["TERMS", "PRIVACY", "IDENTITY_VERIFICATION", "CREDIT_REPORT", "ELECTRONIC_COMMUNICATIONS", "INVESTMENT_AGREEMENT", "LOAN_AGREEMENT"] } } } } } }, responses: { "201": { description: "Consent recorded" }, "400": { description: "Unknown consent type" } } } },
  "/api/v1/me/payout-accounts": { post: { tags: ["Profile"], security: bearer, summary: "Legacy investor payout account save (prefer /investor/payout-accounts)", responses: { "200": { description: "Saved or change request queued" }, "400": { description: "Invalid account details" } } } },
  "/api/v1/me/payout-accounts/{id}/verify": { post: { tags: ["Profile"], security: bearer, summary: "Legacy investor payout account verification trigger", parameters: [{ name: "id", in: "path", required: true, schema: { type: "string" } }], responses: { "202": { description: "Verification queued" }, "404": { description: "Account not found" } } } }
};

const kycPaths = {
  "/api/v1/me/kyc": { get: { tags: ["KYC"], security: bearer, summary: "KYC checklist, case status and document list", responses: { "200": { description: "KYC checklist" } } }, post: { tags: ["KYC"], security: bearer, summary: "Submit KYC checklist / BVN / NIN or request verification", requestBody: { required: false, content: { "application/json": { schema: { type: "object", properties: { statusOverride: { type: "string", enum: ["IN_PROGRESS", "PENDING_VERIFICATION"] }, bvn: { type: "string", example: "22212345678" }, nin: { type: "string", example: "12345678901" }, checklist: { type: "object", properties: { bvn: { type: "boolean" }, nin: { type: "boolean" }, proofOfAddress: { type: "boolean" }, passport: { type: "boolean" }, signature: { type: "boolean" } } } } } } } }, responses: { "200": { description: "KYC case updated" }, "400": { description: "Invalid payload" } } } },
  "/api/v1/me/kyc/reuse-application-documents": { post: { tags: ["KYC"], security: bearer, summary: "Copy documents already uploaded on a loan application into the KYC case (skip re-upload)", responses: { "200": { description: "Documents reused where matching files existed" } } } },
  "/api/v1/me/kyc/action-blocked": { post: { tags: ["KYC"], security: bearer, summary: "Report a KYC-blocked user action (telemetry used to drive reminders)", responses: { "202": { description: "Recorded" } } } },
  "/api/v1/me/kyc/bvn/verify": { post: { tags: ["KYC"], security: bearer, summary: "Verify a Bank Verification Number via Prembly", requestBody: { required: true, content: { "application/json": { schema: { type: "object", required: ["bvn"], properties: { bvn: { type: "string", example: "22212345678" }, lastName: { type: "string" }, dateOfBirth: { type: "string" } } } } } }, responses: { "200": { description: "BVN verified against the provided name/DOB" }, "400": { description: "Verification failed" }, "502": { description: "Prembly unavailable" } } } },
  "/api/v1/me/kyc/nin/verify": { post: { tags: ["KYC"], security: bearer, summary: "Verify a National Identification Number via Prembly", requestBody: { required: true, content: { "application/json": { schema: { type: "object", required: ["nin"], properties: { nin: { type: "string", example: "12345678901" }, lastName: { type: "string" }, dateOfBirth: { type: "string" } } } } } }, responses: { "200": { description: "NIN verified" }, "400": { description: "Verification failed" }, "502": { description: "Prembly unavailable" } } } },
  "/api/v1/me/kyc/liveness/verify": { post: { tags: ["KYC"], security: bearer, summary: "Submit a selfie for liveness / face comparison (multipart image)", requestBody: { required: true, content: { "multipart/form-data": { schema: { type: "object", required: ["image"], properties: { image: { type: "string", format: "binary" } } } } } }, responses: { "200": { description: "Liveness result recorded" }, "400": { description: "Liveness check failed" } } } },
  "/api/v1/me/kyc/prembly-widget/complete": { post: { tags: ["KYC"], security: bearer, summary: "Finalize KYC after the Prembly embedded widget flow returns", responses: { "200": { description: "KYC case updated from the widget result" }, "400": { description: "Widget data invalid" } } } },
  "/api/v1/me/kyc/verify-confirm-otp": { post: { tags: ["KYC"], security: bearer, summary: "Confirm the KYC verification OTP (Prembly identity flows)", responses: { "200": { description: "Verification confirmed" }, "400": { description: "Invalid code" } } } },
  "/api/v1/me/kyc/verify-resend-otp": { post: { tags: ["KYC"], security: bearer, summary: "Resend the KYC verification OTP", responses: { "200": { description: "OTP re-sent" } } } },
  "/api/v1/me/kyc/documents": { post: { tags: ["KYC"], security: bearer, summary: "Upload a private KYC document to Google Drive", requestBody: { required: true, content: { "multipart/form-data": { schema: { type: "object", required: ["documentType", "document"], properties: { documentType: { type: "string", example: "proof_of_address" }, document: { type: "string", format: "binary" } } } } } }, responses: { "201": { description: "Private document stored" }, "400": { description: "Invalid upload" }, "503": { description: "Google Drive is not configured or unavailable" } } } },
  "/api/v1/me/documents/{documentId}": { get: { tags: ["KYC"], security: bearer, summary: "Download one of your own documents", parameters: [{ name: "documentId", in: "path", required: true, schema: { type: "string" } }], responses: { "200": { description: "Document stream" }, "403": { description: "Not your document" }, "404": { description: "Document not found" } } } }
};

const investorPaths = {
  "/api/v1/investor/dashboard": { get: { tags: ["Investor"], security: bearer, summary: "Investor dashboard with wallet, active investments, returns and analytics", responses: { "200": { description: "Dashboard payload (held balance is reconciled on read)" }, "403": { description: "Requires INVESTOR role" } } } },
  "/api/v1/investor/wallet": { get: { tags: ["Investor"], security: bearer, summary: "Wallet balances (available, held, pending deposits/payouts, total credited/debited) with reconciliation", responses: { "200": { description: "Wallet with ledger truth" }, "403": { description: "Requires INVESTOR role" } } } },
  "/api/v1/investor/wallet/funding": { post: { tags: ["Investor"], security: bearer, summary: "Create a wallet funding intent (Flutterwave payment link)", requestBody: { required: true, content: { "application/json": { schema: { $ref: "#/components/schemas/Amount" } } } }, responses: { "202": { description: "Funding intent created with checkout link" }, "400": { description: "amountNaira must be a positive number" } } } },
  "/api/v1/investor/wallet/funding/verify": { post: { tags: ["Investor"], security: bearer, summary: "Verify a Flutterwave transaction to credit a pending deposit", requestBody: { required: true, content: { "application/json": { schema: { type: "object", required: ["transactionId"], properties: { transactionId: { type: "string" } } } } } }, responses: { "200": { description: "Deposit credited" }, "422": { description: "Verification mismatch (amount/currency/owner)" }, "503": { description: "Flutterwave unavailable" } } } },
  "/api/v1/investor/wallet/withdraw": { post: { tags: ["Investor"], security: bearer, summary: "Withdraw from available balance to a Nigerian bank account (OTP-protected, idempotent)", requestBody: { required: true, content: { "application/json": { schema: { type: "object", required: ["amountNaira", "bankCode", "accountNumber", "idempotencyKey", "otpChallengeId", "otpCode"], properties: { amountNaira: { type: "number", example: 50000 }, bankCode: { type: "string", example: "058" }, accountNumber: { type: "string", example: "0123456789" }, narration: { type: "string" }, idempotencyKey: { type: "string", minLength: 16 }, otpChallengeId: { type: "string" }, otpCode: { type: "string", example: "123456" } } } } } }, responses: { "202": { description: "Withdrawal initiated (Flutterwave transfer)" }, "200": { description: "Idempotent replay of an existing withdrawal (success or failure)" }, "400": { description: "Invalid payload or OTP" }, "409": { description: "Insufficient available balance / KYC required" } } } },
  "/api/v1/investor/investment-plans": { get: { tags: ["Investor"], security: bearer, summary: "Active investment plans (rates, tenures, liquidity rules)", responses: { "200": { description: "Investment plans" } } } },
  "/api/v1/investor/investments": { get: { tags: ["Investor"], security: bearer, summary: "Your investments with status, maturity and expected earnings", responses: { "200": { description: "Investments" } } }, post: { tags: ["Investor"], security: bearer, summary: "Create an investment from available wallet balance (locks the principal)", requestBody: { required: true, content: { "application/json": { schema: { type: "object", required: ["amountNaira"], properties: { amountNaira: { type: "number", example: 100000 }, planId: { type: "string", nullable: true } } } } } }, responses: { "201": { description: "Investment created with maturity date and expected earnings" }, "409": { description: "KYC_REQUIRED or insufficient available balance" } } } },
  "/api/v1/investor/investments/{id}/liquidity": { post: { tags: ["Investor"], security: bearer, summary: "Request early liquidity on an active investment (plan must allow it; fees may apply)", parameters: [{ name: "id", in: "path", required: true, schema: { type: "string", format: "uuid" } }], responses: { "202": { description: "Liquidity request queued for processing" }, "404": { description: "Investment not found" }, "409": { description: "Not active / plan forbids early exit / no verified payout account / KYC required" } } } },
  "/api/v1/investor/withdrawals/status": { get: { tags: ["Investor"], security: bearer, summary: "Live status of your recent withdrawals (reconciles stuck PROCESSING rows)", responses: { "200": { description: "Withdrawal statuses" } } } },
  "/api/v1/investor/transactions": { get: { tags: ["Investor"], security: bearer, summary: "Unified transaction history (deduplicated: funding, investments, returns, withdrawals)", responses: { "200": { description: "Transactions" } } } },
  "/api/v1/investor/payout-account": { get: { tags: ["Investor"], security: bearer, summary: "Legacy single payout account view (prefer /investor/payout-accounts)", responses: { "200": { description: "Configured payout account" } } }, put: { tags: ["Investor"], security: bearer, summary: "Legacy payout account save — later changes become approval requests", responses: { "202": { description: "Payout account saved for verification" } } } },
  "/api/v1/investor/payout-accounts": { get: { tags: ["Investor"], security: bearer, summary: "List your payout accounts with default flag and verification status", responses: { "200": { description: "Payout accounts" } } }, post: { tags: ["Investor"], security: bearer, summary: "Save a payout account (first account is auto-verified default; subsequent changes queue an admin approval request)", requestBody: { required: true, content: { "application/json": { schema: { type: "object", required: ["accountName", "accountNumber", "bankCode"], properties: { accountName: { type: "string" }, accountNumber: { type: "string", example: "0123456789" }, bankCode: { type: "string", example: "058" }, bankName: { type: "string" } } } } } }, responses: { "200": { description: "Saved, or change request queued for admin approval" }, "400": { description: "Invalid account details" } } } },
  "/api/v1/investor/payout-accounts/resolve": { post: { tags: ["Investor"], security: bearer, summary: "Resolve an account number to a name via Flutterwave before saving", requestBody: { required: true, content: { "application/json": { schema: { type: "object", required: ["accountNumber", "bankCode"], properties: { accountNumber: { type: "string", example: "0123456789" }, bankCode: { type: "string", example: "058" } } } } } }, responses: { "200": { description: "Resolved account name" }, "400": { description: "Could not resolve account" }, "503": { description: "Flutterwave unavailable" } } } },
  "/api/v1/investor/payout-accounts/{accountId}": { put: { tags: ["Investor"], security: bearer, summary: "Update an existing payout account (queues an approval request)", parameters: [{ name: "accountId", in: "path", required: true, schema: { type: "string" } }], responses: { "202": { description: "Update request queued" }, "404": { description: "Account not found" } } } },
  "/api/v1/investor/payout-accounts/{accountId}/default": { put: { tags: ["Investor"], security: bearer, summary: "Set a payout account as the default for payouts", parameters: [{ name: "accountId", in: "path", required: true, schema: { type: "string" } }], responses: { "200": { description: "Default updated" }, "404": { description: "Account not found" } } } },
  "/api/v1/investor/export/{dataset}": { get: { tags: ["Investor"], security: bearer, summary: "Download your data as CSV", parameters: [{ name: "dataset", in: "path", required: true, schema: { type: "string", enum: ["transactions", "investments", "repayments", "loans", "schedule"] } }, { name: "from", in: "query", schema: { type: "string", format: "date" } }, { name: "to", in: "query", schema: { type: "string", format: "date" } }], responses: { "200": { description: "text/csv attachment (dedup rules mirror the app)" }, "400": { description: "Unknown dataset (hint returned)" } } } }
};

const borrowerPaths = {
  "/api/v1/borrower/dashboard": { get: { tags: ["Borrower"], security: bearer, summary: "Borrower dashboard: application state, loans, next action CTA", responses: { "200": { description: "Dashboard (CTA is honest per application/loan status)" }, "403": { description: "Requires BORROWER role" } } } },
  "/api/v1/borrower/applications/reapply-prefill": { get: { tags: ["Borrower"], security: bearer, summary: "Reapply prefill: merge EVERY previous application snapshot (newest wins) with the account profile, verified KYC case and saved disbursement account so a returning customer never re-types their information", responses: { "200": { description: "{ prefill (personalInfo, disbursementAccount, personalFinancial, businessInfo, businessRep, businessFinancial, kyc, collateral, witness, loanRequest), meta { hasPreviousApplication, sourceApplicationId, sources } }" }, "403": { description: "Requires BORROWER role" } } } },
  "/api/v1/borrower/loan-products": { get: { tags: ["Borrower"], security: bearer, summary: "Active loan products with explicit flow type, amounts (incl. default), tenor list, interest, fees and tenures", parameters: [{ name: "type", in: "query", schema: { type: "string", enum: ["PERSONAL", "BUSINESS"] }, description: "Returns the SINGLE authoritative product for that borrower flow" }, { name: "productId", in: "query", schema: { type: "string" } }], responses: { "200": { description: "Loan products (resilient to catalog misconfiguration; each carries programType PERSONAL/BUSINESS/BOTH)" } } } },
  "/api/v1/borrower/application-draft": { get: { tags: ["Borrower"], security: bearer, summary: "Fetch your in-flight application draft (self-heals: drafts of repaid/cancelled applications are purged)", responses: { "200": { description: "Draft or null" } } }, put: { tags: ["Borrower"], security: bearer, summary: "Save or update your application draft (cloud save & resume)", requestBody: { required: true, content: { "application/json": { schema: { type: "object", properties: { applicationId: { type: "string" }, draft: { type: "object", additionalProperties: true } } } } } }, responses: { "200": { description: "Draft saved" }, "409": { description: "Draft belongs to a terminal application and was purged" } } } },
  "/api/v1/borrower/application-draft/{applicationId}": { delete: { tags: ["Borrower"], security: bearer, summary: "Delete an application draft", parameters: [{ name: "applicationId", in: "path", required: true, schema: { type: "string" } }], responses: { "200": { description: "Draft deleted" } } } },
  "/api/v1/borrower/applications": { post: { tags: ["Borrower"], security: bearer, summary: "Create a loan application. A new request always gets a FRESH application ID — reusing the ID of a repaid/cancelled application creates a new record instead", requestBody: { required: true, content: { "application/json": { schema: { type: "object", required: ["applicantType", "loanRequest"], properties: { applicationId: { type: "string", description: "Optional client-generated reference; terminal-status IDs are never reused" }, applicantType: { type: "string", enum: ["PERSONAL", "BUSINESS"] }, loanProductId: { type: "string", description: "Explicit product binding — the product the borrower saw and calculated with; wins over type/amount-based resolution" }, personalInfo: { type: "object", additionalProperties: true }, businessInfo: { type: "object", additionalProperties: true }, businessRep: { type: "object", additionalProperties: true }, personalFinancial: { type: "object", additionalProperties: true }, businessFinancial: { type: "object", additionalProperties: true }, kyc: { type: "object", additionalProperties: true }, disbursementAccount: { type: "object", additionalProperties: true, description: "Verified account where the loan will be paid" }, loanRequest: { type: "object", required: ["amount", "tenure", "purpose"], properties: { amount: { type: "number" }, tenure: { type: "integer" }, purpose: { type: "string" } } }, collateral: { type: "object", additionalProperties: true }, calculation: { type: "object", nullable: true, additionalProperties: true } } } } } }, responses: { "201": { description: "Application created with internal and external credit report snapshots" }, "200": { description: "Duplicate of a non-terminal application (same ID returned, no new record)" }, "400": { description: "Invalid application payload" }, "409": { description: "Application reference ID already in use by another borrower" } } } },
  "/api/v1/borrower/applications/{id}": { patch: { tags: ["Borrower"], security: bearer, summary: "Update a draft application (sections remain editable until submitted)", parameters: [{ name: "id", in: "path", required: true, schema: { type: "string" } }], responses: { "200": { description: "Application updated" }, "404": { description: "Application not found" } } } },
  "/api/v1/borrower/applications/{id}/submit": { post: { tags: ["Borrower"], security: bearer, summary: "Submit a completed application for review", parameters: [{ name: "id", in: "path", required: true, schema: { type: "string" } }], responses: { "200": { description: "Application submitted (UNDER_REVIEW)" }, "409": { description: "Already submitted or missing sections" } } } },
  "/api/v1/borrower/loans": { get: { tags: ["Borrower"], security: bearer, summary: "Your loans with repayment progress", responses: { "200": { description: "Borrower loans" } } } },
  "/api/v1/borrower/loans/{loanId}": { get: { tags: ["Borrower"], security: bearer, summary: "Loan detail with schedule, repayments, customer and credit report snapshots", parameters: [{ name: "loanId", in: "path", required: true, schema: { type: "string", format: "uuid" } }], responses: { "200": { description: "Loan detail" }, "404": { description: "Loan not found" } } } },
  "/api/v1/borrower/credit-score": { get: { tags: ["Borrower"], security: bearer, summary: "Versioned internal credit score with factors", responses: { "200": { description: "Credit score" } } } },
  "/api/v1/borrower/credit-history": { get: { tags: ["Borrower"], security: bearer, summary: "Repayment and credit score event history", responses: { "200": { description: "Credit history" } } } },
  "/api/v1/borrower/credit-report/request": { post: { tags: ["Borrower"], security: bearer, summary: "Request an external credit bureau report (consent-gated; Commercial Business Advance via the profile RC number when available, consumer advance via verified BVN/NIN otherwise). Creates the report as PENDING and finishes in the background", requestBody: { required: true, content: { "application/json": { schema: { type: "object", required: ["consent"], properties: { consent: { type: "boolean", enum: [true], description: "Explicit credit-report consent" } } } } } }, responses: { "200": { description: "{ report, creditScore, message }" }, "400": { description: "Consent missing" }, "409": { description: "No usable identity for a bureau lookup" } } } },
  "/api/v1/borrower/loans/{loanId}/repayments": { post: { tags: ["Borrower"], security: bearer, summary: "Start a loan repayment (Flutterwave checkout; enforces outstanding and minimum limits)", parameters: [{ name: "loanId", in: "path", required: true, schema: { type: "string", format: "uuid" } }], requestBody: { required: true, content: { "application/json": { schema: { $ref: "#/components/schemas/Amount" } } } }, responses: { "201": { description: "Flutterwave checkout initialized" }, "400": { description: "Nothing outstanding, below minimum or above outstanding" }, "404": { description: "Loan not found" }, "503": { description: "Flutterwave unavailable" } } } },
  "/api/v1/borrower/disbursement-account": { get: { tags: ["Borrower"], security: bearer, summary: "Your disbursement account (where loans are paid) and any pending change request", responses: { "200": { description: "Disbursement account" } } }, post: { tags: ["Borrower"], security: bearer, summary: "Save your disbursement account (verified name + 10-digit number + bank; admin approval flow when a loan is blocked on the change)", requestBody: { required: true, content: { "application/json": { schema: { type: "object", required: ["accountName", "accountNumber", "bankCode"], properties: { accountName: { type: "string" }, accountNumber: { type: "string", example: "0123456789" }, bankCode: { type: "string", example: "058" }, bankName: { type: "string" } } } } } }, responses: { "200": { description: "Saved or change request queued" }, "400": { description: "Invalid details or provider rejected the account" } } }, put: { tags: ["Borrower"], security: bearer, summary: "Update your disbursement account (same validation and approval rules)", responses: { "200": { description: "Saved or change request queued" }, "400": { description: "Invalid details" } } } },
  "/api/v1/borrower/disbursement-account/resolve": { post: { tags: ["Borrower"], security: bearer, summary: "Resolve an account number to a name via Flutterwave before saving", requestBody: { required: true, content: { "application/json": { schema: { type: "object", required: ["accountNumber", "bankCode"], properties: { accountNumber: { type: "string" }, bankCode: { type: "string" } } } } } }, responses: { "200": { description: "Resolved account name" }, "400": { description: "Could not resolve account" }, "503": { description: "Flutterwave unavailable" } } } },
  "/api/v1/borrower/export/{dataset}": { get: { tags: ["Borrower"], security: bearer, summary: "Download your data as CSV", parameters: [{ name: "dataset", in: "path", required: true, schema: { type: "string", enum: ["transactions", "investments", "repayments", "loans", "schedule"] } }, { name: "from", in: "query", schema: { type: "string", format: "date" } }, { name: "to", in: "query", schema: { type: "string", format: "date" } }], responses: { "200": { description: "text/csv attachment" }, "400": { description: "Unknown dataset (hint returned)" } } } }
};

const adminPaths = {
  "/api/v1/admin/summary": { get: { tags: ["Admin"], security: bearer, summary: "Platform summary metrics for the admin overview", responses: { "200": { description: "Admin summary" }, "403": { description: "Requires ADMIN role" } } } },
  "/api/v1/admin/users": { get: { tags: ["Admin"], security: bearer, summary: "List users with role/status filters and pagination", parameters: [{ name: "role", in: "query", schema: { type: "string", enum: ["INVESTOR", "BORROWER", "ADMIN", "LOAN_MANAGER"] } }, { name: "status", in: "query", schema: { type: "string", enum: ["ACTIVE", "SUSPENDED"] } }, { name: "limit", in: "query", schema: { type: "integer" } }, { name: "offset", in: "query", schema: { type: "integer" } }], responses: { "200": { description: "Users with meta" } } }, post: { tags: ["Admin"], security: bearer, summary: "Create a customer account (min 12-char password, Nigerian phone)", requestBody: { required: true, content: { "application/json": { schema: { type: "object", required: ["email", "fullName", "phone", "password"], properties: { email: { type: "string", format: "email" }, fullName: { type: "string" }, phone: { type: "string", example: "08012345678" }, password: { type: "string", minLength: 12 }, roles: { type: "array", items: { type: "string", enum: ["INVESTOR", "BORROWER"] } } } } } } }, responses: { "201": { description: "User created" }, "400": { description: "Invalid input" }, "409": { description: "Email already exists" } } } },
  "/api/v1/admin/users/{id}/roles": { patch: { tags: ["Admin"], security: bearer, summary: "Update a user's roles", parameters: [{ name: "id", in: "path", required: true, schema: { type: "string" } }], responses: { "200": { description: "Roles updated" }, "404": { description: "User not found" } } } },
  "/api/v1/admin/users/{id}/status": { patch: { tags: ["Admin"], security: bearer, summary: "Activate or suspend a user", parameters: [{ name: "id", in: "path", required: true, schema: { type: "string" } }], responses: { "200": { description: "Status updated" }, "404": { description: "User not found" } } } },
  "/api/v1/admin/users/{id}": { patch: { tags: ["Admin"], security: bearer, summary: "Update user profile fields (name, phone, email)", parameters: [{ name: "id", in: "path", required: true, schema: { type: "string" } }], responses: { "200": { description: "User updated" }, "404": { description: "User not found" } } } },
  "/api/v1/admin/users/{id}/kyc-reset": { post: { tags: ["Admin"], security: bearer, summary: "Reset a user's KYC case so they can re-verify", parameters: [{ name: "id", in: "path", required: true, schema: { type: "string" } }], responses: { "200": { description: "KYC reset" }, "404": { description: "User not found" } } } },
  "/api/v1/admin/loan-managers": { get: { tags: ["Admin"], security: bearer, summary: "List loan managers and their permissions", responses: { "200": { description: "Loan managers" } } }, post: { tags: ["Admin"], security: bearer, summary: "Create a loan manager account with scoped permissions", requestBody: { required: true, content: { "application/json": { schema: { type: "object", required: ["email", "fullName", "phone", "password"], properties: { email: { type: "string", format: "email" }, fullName: { type: "string" }, phone: { type: "string" }, password: { type: "string", minLength: 12 }, permissions: { type: "array", items: { type: "string" } } } } } } }, responses: { "201": { description: "Loan manager created" }, "409": { description: "Email already exists" } } } },
  "/api/v1/admin/loan-managers/{id}/status": { patch: { tags: ["Admin"], security: bearer, summary: "Activate or suspend a loan manager", parameters: [{ name: "id", in: "path", required: true, schema: { type: "string" } }], responses: { "200": { description: "Status updated" } } } },
  "/api/v1/admin/loan-managers/{id}": { delete: { tags: ["Admin"], security: bearer, summary: "Remove a loan manager", parameters: [{ name: "id", in: "path", required: true, schema: { type: "string" } }], responses: { "200": { description: "Removed" } } } },
  "/api/v1/admin/administrators": { get: { tags: ["Admin"], security: bearer, summary: "List administrator accounts", responses: { "200": { description: "Administrators" } } }, post: { tags: ["Admin"], security: bearer, summary: "Create an administrator account", requestBody: { required: true, content: { "application/json": { schema: { type: "object", required: ["email", "fullName", "phone", "password"], properties: { email: { type: "string", format: "email" }, fullName: { type: "string" }, phone: { type: "string" }, password: { type: "string", minLength: 12 } } } } } }, responses: { "201": { description: "Administrator created" }, "409": { description: "Email already exists" } } } },
  "/api/v1/admin/administrators/{id}/status": { patch: { tags: ["Admin"], security: bearer, summary: "Activate or suspend an administrator", parameters: [{ name: "id", in: "path", required: true, schema: { type: "string" } }], responses: { "200": { description: "Status updated" } } } },
  "/api/v1/admin/administrators/{id}": { delete: { tags: ["Admin"], security: bearer, summary: "Remove an administrator", parameters: [{ name: "id", in: "path", required: true, schema: { type: "string" } }], responses: { "200": { description: "Removed" } } } },
  "/api/v1/admin/audit-logs": { get: { tags: ["Admin"], security: bearer, summary: "Audit trail of sensitive actions with actor and target enrichment", parameters: [{ name: "limit", in: "query", schema: { type: "integer" } }, { name: "offset", in: "query", schema: { type: "integer" } }], responses: { "200": { description: "Audit logs with meta" } } } },
  "/api/v1/admin/kyc-cases": { get: { tags: ["Admin"], security: bearer, summary: "KYC review queue with user details", responses: { "200": { description: "KYC cases" } } } },
  "/api/v1/admin/kyc-cases/{id}/decision": { post: { tags: ["Admin"], security: bearer, summary: "Approve, reject or escalate a KYC case (notifies the user)", parameters: [{ name: "id", in: "path", required: true, schema: { type: "string" } }], requestBody: { required: true, content: { "application/json": { schema: { type: "object", required: ["decision"], properties: { decision: { type: "string", enum: ["VERIFIED", "PARTIALLY_VERIFIED", "REJECTED", "ACTION_REQUIRED", "SUSPENDED"] }, note: { type: "string" }, rejectedReason: { type: "string" }, checklistOverride: { type: "object", properties: { bvn: { type: "boolean" }, nin: { type: "boolean" }, proofOfAddress: { type: "boolean" }, passport: { type: "boolean" }, signature: { type: "boolean" } } } } } } } }, responses: { "200": { description: "Decision saved" }, "404": { description: "KYC case not found" } } } },
  "/api/v1/admin/kyc-cases/{id}/requirement": { post: { tags: ["Admin"], security: bearer, summary: "Approve or reject a single KYC requirement (bvn, nin, liveness, proofOfAddress, passport, signature)", parameters: [{ name: "id", in: "path", required: true, schema: { type: "string" } }], requestBody: { required: true, content: { "application/json": { schema: { type: "object", required: ["requirement", "approved"], properties: { requirement: { type: "string", enum: ["bvn", "nin", "liveness", "proofOfAddress", "passport", "signature"] }, approved: { type: "boolean" }, note: { type: "string" } } } } } }, responses: { "200": { description: "Requirement updated, case re-evaluated" }, "404": { description: "KYC case not found" } } } },
  "/api/v1/admin/application-drafts": { get: { tags: ["Admin"], security: bearer, summary: "List saved application drafts", responses: { "200": { description: "Drafts" } } } },
  "/api/v1/admin/application-drafts/{applicationId}": { get: { tags: ["Admin"], security: bearer, summary: "Inspect one application draft", parameters: [{ name: "applicationId", in: "path", required: true, schema: { type: "string" } }], responses: { "200": { description: "Draft" }, "404": { description: "Draft not found" } } } },
  "/api/v1/admin/loans": { get: { tags: ["Admin"], security: bearer, summary: "Loan applications with customer and credit snapshots (filterable, searchable, paginated)", parameters: [{ name: "limit", in: "query", schema: { type: "integer", default: 50 } }, { name: "offset", in: "query", schema: { type: "integer", default: 0 } }, { name: "status", in: "query", schema: { type: "string" } }, { name: "borrowerId", in: "query", schema: { type: "string", format: "uuid" } }, { name: "search", in: "query", schema: { type: "string" }, description: "Matches name, email, phone or application reference" }], responses: { "200": { description: "{ loans, loanRecords, meta.total }" } } } },
  "/api/v1/admin/loans/{loanId}": { get: { tags: ["Admin"], security: bearer, summary: "Detailed loan review record (application, borrower, documents, credit reports)", parameters: [{ name: "loanId", in: "path", required: true, schema: { type: "string" } }], responses: { "200": { description: "Loan review record" }, "404": { description: "Loan not found" } } } },
  "/api/v1/admin/loans/{loanId}/decision": { post: { tags: ["Admin"], security: bearer, summary: "Record a manual decision on the application", parameters: [{ name: "loanId", in: "path", required: true, schema: { type: "string" } }], requestBody: { required: true, content: { "application/json": { schema: { type: "object", required: ["decision"], properties: { decision: { type: "string", enum: ["APPROVED", "REJECTED", "MORE_INFORMATION_REQUIRED"] }, note: { type: "string" } } } } } }, responses: { "200": { description: "Manual loan decision saved" } } } },
  "/api/v1/admin/loans/{loanId}/stages/{stageKey}": { patch: { tags: ["Admin"], security: bearer, summary: "Approve or reject one application stage in the staged review flow", parameters: [{ name: "loanId", in: "path", required: true, schema: { type: "string" } }, { name: "stageKey", in: "path", required: true, schema: { type: "string" } }], requestBody: { required: true, content: { "application/json": { schema: { type: "object", required: ["decision"], properties: { decision: { type: "string", enum: ["APPROVED", "REJECTED"] }, note: { type: "string", maxLength: 2000 } } } } } }, responses: { "200": { description: "Stage decision saved" }, "404": { description: "Application not found" } } } },
  "/api/v1/admin/loans/{loanId}/stages/approve-all": { post: { tags: ["Admin"], security: bearer, summary: "Approve all outstanding stages at once", parameters: [{ name: "loanId", in: "path", required: true, schema: { type: "string" } }], responses: { "200": { description: "All stages approved" } } } },
  "/api/v1/admin/loans/{loanId}/disburse": { post: { tags: ["Admin"], security: bearer, summary: "Disburse an approved loan to the borrower's verified account via Flutterwave (ledger DEBIT recorded; retriable). Duplicate protection: a DISBURSED/ACTIVE/PAST_DUE/DEFAULTED/REPAID/WRITTEN_OFF loan can never be disbursed again", parameters: [{ name: "loanId", in: "path", required: true, schema: { type: "string" } }], responses: { "202": { description: "Flutterwave transfer initiated" }, "409": { description: "Loan already disbursed and active (code ALREADY_DISBURSED, can't disburse duplicate loan) / manual approval required / disbursement already in progress or completed" }, "503": { description: "Flutterwave unavailable" } } } },
  "/api/v1/admin/loan-applications/{applicationId}/credit-bureau": { post: { tags: ["Admin"], security: bearer, summary: "Trigger a Prembly credit-bureau check for the application borrower — Commercial (Business) Advance via RC number + company name when the profile has them, consumer advance via verified BVN/NIN otherwise. The report row is created immediately (PENDING) and the provider call runs in the background (real lookups take 25-90s, PREMBLY_CREDIT_TIMEOUT_MS); the response waits up to 3s for an inline result, otherwise poll the application detail", parameters: [{ name: "applicationId", in: "path", required: true, schema: { type: "string" } }], requestBody: { content: { "application/json": { schema: { type: "object", properties: { dataMode: { type: "string", enum: ["BASIC", "ADVANCE"], default: "ADVANCE", description: "Prembly commercial report depth" } } } } } }, responses: { "200": { description: "{ report, creditReportSnapshot, message }" }, "404": { description: "Loan application not found" }, "409": { description: "No usable identity (no RC number, BVN or name) for a bureau lookup" }, "502": { description: "Provider call failed unexpectedly" } } } },
  "/api/v1/admin/loans/{loanId}/request-account-update": { post: { tags: ["Admin"], security: bearer, summary: "Ask the borrower to update their disbursement account (blocks disbursal until resolved)", parameters: [{ name: "loanId", in: "path", required: true, schema: { type: "string" } }], responses: { "202": { description: "Request sent to the borrower" } } } },
  "/api/v1/admin/documents/{documentId}": { get: { tags: ["Admin"], security: bearer, summary: "Stream an applicant document for review", parameters: [{ name: "documentId", in: "path", required: true, schema: { type: "string" } }], responses: { "200": { description: "Document stream" }, "404": { description: "Document not found" } } } }
};

const adminOpsPaths = {
  "/api/v1/admin/investors": { get: { tags: ["Admin"], security: bearer, summary: "Investors with investment history and wallet summaries", responses: { "200": { description: "Investors" } } } },
  "/api/v1/admin/investors/{investorId}/earning-rate": { put: { tags: ["Admin"], security: bearer, summary: "Set a bespoke annual earning rate for one investor (overrides plan rate)", parameters: [{ name: "investorId", in: "path", required: true, schema: { type: "string" } }], requestBody: { required: true, content: { "application/json": { schema: { type: "object", required: ["annualRatePercent"], properties: { annualRatePercent: { type: "number", minimum: 0, maximum: 100 } } } } } }, responses: { "200": { description: "Earning rate saved" } } } },
  "/api/v1/admin/investors/{investorId}/credit-wallet": { post: { tags: ["Admin"], security: bearer, summary: "Manually credit an investor wallet with a ledgered, audited entry", parameters: [{ name: "investorId", in: "path", required: true, schema: { type: "string" } }], requestBody: { required: true, content: { "application/json": { schema: { type: "object", required: ["amountNaira"], properties: { amountNaira: { type: "number", maximum: 500000000 }, description: { type: "string" }, reason: { type: "string", enum: ["MANUAL_CREDIT", "INVESTMENT_RETURN", "BONUS", "CORRECTION"] } } } } } }, responses: { "200": { description: "Wallet credited and audit-logged" }, "404": { description: "Investor not found" } } } },
  "/api/v1/admin/investors/{investorId}/withdrawals": { get: { tags: ["Admin"], security: bearer, summary: "Withdrawal history for one investor", parameters: [{ name: "investorId", in: "path", required: true, schema: { type: "string" } }], responses: { "200": { description: "Investor withdrawals" }, "404": { description: "Investor not found" } } } },
  "/api/v1/admin/investments": { get: { tags: ["Admin"], security: bearer, summary: "All investments with investor details (paginated)", responses: { "200": { description: "Investments with meta" } } } },
  "/api/v1/admin/ledger": { get: { tags: ["Admin"], security: bearer, summary: "Double-entry admin ledger with platform balance (filterable by entry type)", parameters: [{ name: "limit", in: "query", schema: { type: "integer", default: 100, maximum: 500 } }, { name: "offset", in: "query", schema: { type: "integer" } }, { name: "entryType", in: "query", schema: { type: "string" } }], responses: { "200": { description: "Ledger entries + balanceMinor/balanceNaira + totals" } } } },
  "/api/v1/admin/withdrawals": { get: { tags: ["Admin"], security: bearer, summary: "All investor withdrawals with status/date filters, search and pagination", parameters: [{ name: "status", in: "query", schema: { type: "string" } }, { name: "search", in: "query", schema: { type: "string" } }, { name: "from", in: "query", schema: { type: "string", format: "date" } }, { name: "to", in: "query", schema: { type: "string", format: "date" } }, { name: "limit", in: "query", schema: { type: "integer" } }, { name: "offset", in: "query", schema: { type: "integer" } }], responses: { "200": { description: "Withdrawals with investor enrichment" } } } },
  "/api/v1/admin/withdrawals/{withdrawalId}/detail": { get: { tags: ["Admin"], security: bearer, summary: "Withdrawal detail with ledger trail, timeline and provider references", parameters: [{ name: "withdrawalId", in: "path", required: true, schema: { type: "string" } }], responses: { "200": { description: "Withdrawal detail" }, "404": { description: "Withdrawal not found" } } } },
  "/api/v1/admin/withdrawals/{withdrawalId}/retry": { post: { tags: ["Admin"], security: bearer, summary: "Retry a failed investor withdrawal via Flutterwave", parameters: [{ name: "withdrawalId", in: "path", required: true, schema: { type: "string" } }], responses: { "202": { description: "Retry initiated" }, "409": { description: "Only failed withdrawals can be retried" }, "503": { description: "Flutterwave unavailable" } } } },
  "/api/v1/admin/payouts": { get: { tags: ["Admin"], security: bearer, summary: "All investor payout attempts", responses: { "200": { description: "Payouts" } } } },
  "/api/v1/admin/payouts/{payoutId}/retry": { post: { tags: ["Admin"], security: bearer, summary: "Manually retry a failed payout", parameters: [{ name: "payoutId", in: "path", required: true, schema: { type: "string", format: "uuid" } }], responses: { "202": { description: "Manual payout retry initiated" }, "503": { description: "Flutterwave unavailable" } } } },
  "/api/v1/admin/payouts/{payoutId}/approve": { post: { tags: ["Admin"], security: bearer, summary: "Approve a payout that is pending manual approval", parameters: [{ name: "payoutId", in: "path", required: true, schema: { type: "string" } }], responses: { "202": { description: "Payout approved and queued for transfer" }, "409": { description: "Not awaiting approval" } } } },
  "/api/v1/admin/disbursements": { get: { tags: ["Admin"], security: bearer, summary: "All loan disbursements (self-heals stuck PROCESSING rows against the provider on read)", parameters: [{ name: "status", in: "query", schema: { type: "string" } }, { name: "limit", in: "query", schema: { type: "integer" } }, { name: "offset", in: "query", schema: { type: "integer" } }], responses: { "200": { description: "Disbursements with borrower names" } } } },
  "/api/v1/admin/borrowers/{borrowerId}/disbursements": { get: { tags: ["Admin"], security: bearer, summary: "Disbursement history for one borrower", parameters: [{ name: "borrowerId", in: "path", required: true, schema: { type: "string" } }], responses: { "200": { description: "Borrower disbursements" } } } },
  "/api/v1/admin/disbursements/{disbursementId}/retry": { post: { tags: ["Admin"], security: bearer, summary: "Retry a failed loan disbursement transfer (blocked with ALREADY_DISBURSED when the loan has already settled)", parameters: [{ name: "disbursementId", in: "path", required: true, schema: { type: "string" } }], responses: { "202": { description: "Retry initiated" }, "409": { description: "Only failed disbursements can be retried / loan already disbursed and active, can't disburse duplicate loan" } } } },
  "/api/v1/admin/account-requests": { get: { tags: ["Admin"], security: bearer, summary: "Pending bank-account change requests (payout and disbursement accounts)", responses: { "200": { description: "Account change requests" } } } },
  "/api/v1/admin/account-requests/{requestId}/approve": { put: { tags: ["Admin"], security: bearer, summary: "Approve an account change request and apply the new account", parameters: [{ name: "requestId", in: "path", required: true, schema: { type: "string" } }], responses: { "200": { description: "Change applied" }, "400": { description: "Unable to apply changes" }, "409": { description: "Already processed" } } } },
  "/api/v1/admin/account-requests/{requestId}/reject": { put: { tags: ["Admin"], security: bearer, summary: "Reject an account change request with an optional reason", parameters: [{ name: "requestId", in: "path", required: true, schema: { type: "string" } }], requestBody: { required: false, content: { "application/json": { schema: { type: "object", properties: { rejectionReason: { type: "string", maxLength: 500 } } } } } }, responses: { "200": { description: "Request rejected" }, "409": { description: "Already processed" } } } },
  "/api/v1/admin/investment-plans": { get: { tags: ["Admin"], security: bearer, summary: "All investment plans including inactive", responses: { "200": { description: "Investment plans" } } }, post: { tags: ["Admin"], security: bearer, summary: "Create an investment plan", requestBody: { required: true, content: { "application/json": { schema: { type: "object", required: ["name", "minAmountNaira", "maxAmountNaira", "tenureDays", "annualRatePercent"], properties: { name: { type: "string" }, description: { type: "string" }, minAmountNaira: { type: "number" }, maxAmountNaira: { type: "number" }, tenureDays: { type: "integer" }, annualRatePercent: { type: "number" }, rateType: { type: "string", enum: ["ANNUALIZED", "FLAT", "TENURE_SPECIFIC"] }, earlyLiquidityAllowed: { type: "boolean" }, earlyLiquidityFeePercent: { type: "number" }, gatewayFeePercent: { type: "number" }, forfeitInterestOnEarlyExit: { type: "boolean" }, capacityNaira: { type: "number" }, isActive: { type: "boolean" } } } } } }, responses: { "201": { description: "Plan created" }, "400": { description: "Invalid plan" } } } },
  "/api/v1/admin/investment-plans/{id}": { patch: { tags: ["Admin"], security: bearer, summary: "Update an investment plan (rate, liquidity rules, active flag…)", parameters: [{ name: "id", in: "path", required: true, schema: { type: "string" } }], responses: { "200": { description: "Plan updated" }, "404": { description: "Plan not found" } } } },
  "/api/v1/admin/loan-products": { get: { tags: ["Admin"], security: bearer, summary: "All loan products including inactive", responses: { "200": { description: "Loan products" } } }, post: { tags: ["Admin"], security: bearer, summary: "Create a loan product with the FULL configuration (type, amounts incl. default, tenor list, fees incl. service fee, collateral; validates default amount inside range and default tenor in list)", requestBody: { required: true, content: { "application/json": { schema: { type: "object", required: ["name", "minAmountNaira", "maxAmountNaira", "interestRatePercent"], properties: { name: { type: "string" }, description: { type: "string" }, programType: { type: "string", enum: ["PERSONAL", "BUSINESS", "BOTH"], nullable: true, description: "Explicit borrower-flow mapping; null falls back to legacy name-keyword classification" }, minAmountNaira: { type: "number" }, maxAmountNaira: { type: "number" }, defaultAmountNaira: { type: "number", description: "Pre-selected amount on the borrower form; must fall within min/max" }, defaultTenureDays: { type: "integer", description: "Must be one of tenureDays when both are set" }, tenureDays: { type: "array", items: { type: "integer" }, description: "Allowed tenor list (days) — the borrower tenure picker renders exactly this; deduped + sorted" }, tenorInterestRates: { type: "array", description: "Per-tenor MONTHLY interest rates (easimoney style): interest for tenor T = principal × monthlyRatePercent% × (T/30); entries must reference tenureDays tenors. status marks the tenor AVAILABLE (default), LOCKED (visible to borrowers but not selectable, rate hidden) or HOT (selectable + Hot badge)", items: { type: "object", properties: { tenorDays: { type: "integer" }, monthlyRatePercent: { type: "number" }, status: { type: "string", enum: ["AVAILABLE", "LOCKED", "HOT"] } } } }, interestRatePercent: { type: "number" }, interestType: { type: "string", enum: ["SIMPLE_FLAT", "REDUCING_BALANCE", "ANNUALIZED"] }, processingFeePercent: { type: "number" }, serviceFeePercent: { type: "number" }, lateFeePercent: { type: "number" }, lateFeeType: { type: "string", enum: ["ONE_TIME", "COMPOUNDING_DAILY", "COMPOUNDING_MONTHLY"] }, gracePeriodDays: { type: "integer" }, collateralEnabled: { type: "boolean" }, collateralRequired: { type: "boolean" }, isActive: { type: "boolean" } } } } } }, responses: { "201": { description: "Product created" }, "400": { description: "Invalid product (min >= max, default amount outside range, default tenor not in list, per-tenor rate referencing an unknown tenor)" }, "409": { description: "Duplicate product name" } } } },
  "/api/v1/admin/loan-products/{id}": { patch: { tags: ["Admin"], security: bearer, summary: "Update any loan product field (programType, amounts, default amount, tenureDays list, service fee, collateral flags); merged product is re-validated", parameters: [{ name: "id", in: "path", required: true, schema: { type: "string" } }], requestBody: { required: true, content: { "application/json": { schema: { type: "object", properties: { name: { type: "string" }, description: { type: "string" }, programType: { type: "string", enum: ["PERSONAL", "BUSINESS", "BOTH"], nullable: true }, minAmountNaira: { type: "number" }, maxAmountNaira: { type: "number" }, defaultAmountNaira: { type: "number", nullable: true }, defaultTenureDays: { type: "integer" }, tenureDays: { type: "array", items: { type: "integer" } }, tenorInterestRates: { type: "array", nullable: true, description: "Per-tenor MONTHLY interest rates (easimoney style); entries must reference the tenureDays list; empty array clears the map; shrinking the tenor list prunes orphaned entries. status: AVAILABLE (default) / LOCKED (visible but not selectable, rate hidden) / HOT (selectable + Hot badge)", items: { type: "object", properties: { tenorDays: { type: "integer" }, monthlyRatePercent: { type: "number" }, status: { type: "string", enum: ["AVAILABLE", "LOCKED", "HOT"] } } } }, interestRatePercent: { type: "number" }, interestType: { type: "string", enum: ["SIMPLE_FLAT", "REDUCING_BALANCE", "ANNUALIZED"] }, processingFeePercent: { type: "number" }, serviceFeePercent: { type: "number" }, lateFeePercent: { type: "number" }, lateFeeType: { type: "string", enum: ["ONE_TIME", "COMPOUNDING_DAILY", "COMPOUNDING_MONTHLY"] }, gracePeriodDays: { type: "integer" }, collateralEnabled: { type: "boolean" }, collateralRequired: { type: "boolean" }, isActive: { type: "boolean" } } } } } }, responses: { "200": { description: "Product updated" }, "400": { description: "Merged product invalid (inverted range, default amount outside range, default tenor not in list, per-tenor rate referencing an unknown tenor)" }, "404": { description: "Product not found" }, "409": { description: "Another product already uses the new name" } } } },
  "/api/v1/admin/settings/platform": { get: { tags: ["Admin"], security: bearer, summary: "Platform settings (fees, rates, maintenance mode, announcements, banners)", responses: { "200": { description: "Platform settings" } } }, put: { tags: ["Admin"], security: bearer, summary: "Update platform settings (partial update)", requestBody: { required: true, content: { "application/json": { schema: { type: "object", properties: { investorWithdrawalFeePercent: { type: "number" }, investorWithdrawalFeeFlatNaira: { type: "number" }, investorWithdrawalMinAmountNaira: { type: "number" }, defaultInvestmentAnnualRatePercent: { type: "number" }, maintenanceMode: { type: "boolean" }, maintenanceMessage: { type: "string", maxLength: 500 } } } } } }, responses: { "200": { description: "Settings saved" }, "400": { description: "Invalid settings" } } } },
  "/api/v1/admin/announcements": { get: { tags: ["Admin"], security: bearer, summary: "All in-app announcements", responses: { "200": { description: "Announcements" } } }, post: { tags: ["Admin"], security: bearer, summary: "Publish an announcement (max 280 chars)", requestBody: { required: true, content: { "application/json": { schema: { type: "object", required: ["message"], properties: { message: { type: "string", minLength: 3, maxLength: 280 } } } } } }, responses: { "201": { description: "Announcement created" }, "400": { description: "Invalid message" } } } },
  "/api/v1/admin/announcements/{id}": { patch: { tags: ["Admin"], security: bearer, summary: "Edit or activate/deactivate an announcement", parameters: [{ name: "id", in: "path", required: true, schema: { type: "string" } }], responses: { "200": { description: "Announcement updated" }, "404": { description: "Announcement not found" } } }, delete: { tags: ["Admin"], security: bearer, summary: "Delete an announcement", parameters: [{ name: "id", in: "path", required: true, schema: { type: "string" } }], responses: { "200": { description: "Announcement deleted" } } } },
  "/api/v1/admin/banners": { get: { tags: ["Admin"], security: bearer, summary: "All marketing banners", responses: { "200": { description: "Banners" } } }, post: { tags: ["Admin"], security: bearer, summary: "Upload a banner (base64 or data URL image, optional link)", requestBody: { required: true, content: { "application/json": { schema: { type: "object", required: ["name", "imageData"], properties: { name: { type: "string", maxLength: 120 }, imageData: { type: "string" }, mimeType: { type: "string", example: "image/png" }, linkUrl: { type: "string" } } } } } }, responses: { "201": { description: "Banner created (image data omitted from response)" }, "400": { description: "Invalid banner" } } } },
  "/api/v1/admin/banners/{id}": { patch: { tags: ["Admin"], security: bearer, summary: "Edit, link or activate/deactivate a banner", parameters: [{ name: "id", in: "path", required: true, schema: { type: "string" } }], responses: { "200": { description: "Banner updated" }, "404": { description: "Banner not found" } } }, delete: { tags: ["Admin"], security: bearer, summary: "Delete a banner", parameters: [{ name: "id", in: "path", required: true, schema: { type: "string" } }], responses: { "200": { description: "Banner deleted" } } } },
  "/api/v1/admin/reconciliation": { get: { tags: ["Admin"], security: bearer, summary: "Financial reconciliation view (wallet invariants, hold integrity, provider pending items)", responses: { "200": { description: "Reconciliation report" } } } },
  "/api/v1/admin/reports": { get: { tags: ["Admin"], security: bearer, summary: "Business reports over a date range (investments, loans, KYC)", parameters: [{ name: "from", in: "query", schema: { type: "string", format: "date-time" } }, { name: "to", in: "query", schema: { type: "string", format: "date-time" } }], responses: { "200": { description: "Aggregated report (Africa/Lagos currency NGN)" } } } },
  "/api/v1/admin/export/{dataset}": { get: { tags: ["Admin"], security: bearer, summary: "Download a dataset as CSV (withdrawals, loans, payouts, ledger, kyc, investors, audit-logs, investments, disbursements, applications…)", parameters: [{ name: "dataset", in: "path", required: true, schema: { type: "string" } }, { name: "from", in: "query", schema: { type: "string", format: "date" } }, { name: "to", in: "query", schema: { type: "string", format: "date" } }], responses: { "200": { description: "text/csv attachment" }, "400": { description: "Unknown dataset (hint lists valid datasets)" } } } }
};

const paymentsAndWebhookPaths = {
  "/api/v1": { get: { tags: ["Health"], summary: "API index — service name, version and docs link", responses: { "200": { description: "API metadata" } } } },
  "/api/v1/payments/flutterwave/return": { get: { tags: ["Payments"], summary: "Browser landing page after a Flutterwave checkout (redirects back into the app with the transaction reference)", responses: { "200": { description: "HTML redirect page" } } } },
  "/api/v1/providers/flutterwave/banks": { get: { tags: ["Providers"], security: bearer, summary: "Nigerian bank list with Flutterwave bank codes (cached; mapping normalises names)", responses: { "200": { description: "Banks [{ code, name }]" }, "503": { description: "Flutterwave unavailable" } } } },
  "/api/v1/webhooks/flutterwave": { post: { tags: ["Webhooks"], summary: "Receive verified Flutterwave events (idempotent; signature checked)", responses: { "202": { description: "Accepted for idempotent processing" }, "401": { description: "Invalid signature" } } } },
  "/api/v1/webhooks/meta-whatsapp": { get: { tags: ["Webhooks"], summary: "Verify Meta webhook subscription (hub.challenge)", responses: { "200": { description: "Challenge returned" }, "403": { description: "Verification failed" } } }, post: { tags: ["Webhooks"], summary: "Receive verified Meta WhatsApp events (delivery, OTP replies)", responses: { "202": { description: "Accepted for idempotent processing" }, "401": { description: "Invalid signature" } } } },
  "/api/v1/webhooks/prembly": { get: { tags: ["Webhooks"], summary: "Prembly webhook endpoint info", responses: { "200": { description: "Service description" } } }, post: { tags: ["Webhooks"], summary: "Receive Prembly verification events (identity checks), validated when PREMBLY_WEBHOOK_SECRET is configured", responses: { "202": { description: "Accepted for processing" }, "401": { description: "Invalid signature" } } } },
  "/api/v1/webhooks/prembly/kyc": { get: { tags: ["Webhooks"], summary: "Prembly KYC liveness webhook info (expects x-prembly-signature HMAC-SHA512)", responses: { "200": { description: "Service description" } } }, post: { tags: ["Webhooks"], summary: "Receive signature-verified Prembly KYC liveness events", responses: { "202": { description: "Accepted for idempotent processing" }, "401": { description: "Invalid signature" } } } },
  "/api/v1/webhooks/kudi": { get: { tags: ["Webhooks"], summary: "Kudi webhook endpoint info", responses: { "200": { description: "Service description" } } }, post: { tags: ["Webhooks"], summary: "Receive Kudi SMS delivery events (OTP replies), validated when KUDI_WEBHOOK_SECRET is configured", responses: { "202": { description: "Accepted for processing" }, "401": { description: "Invalid signature" } } } }
};

export const openapi = {
  openapi: "3.0.3",
  info: {
    title: "Velo Finance API",
    version: "2.0.0",
    description: "Role-based Nigerian lending and investment platform API (api.velocredit.ng). Covers authentication with OTP, KYC (BVN/NIN/liveness via Prembly), investor wallets with held-balance reconciliation, investments and early liquidity, borrower loan applications with staged review, admin operations, Flutterwave payouts/repayments/disbursements, CSV exports and platform content. Provider settlement remains server-side and webhook-confirmed."
  },
  servers: [
    { url: "https://api.velocredit.ng", description: "Production" },
    { url: "http://localhost:4000", description: "Local development" }
  ],
  tags: [
    { name: "Health", description: "Liveness and API document" },
    { name: "Platform", description: "Public platform status and content" },
    { name: "Auth", description: "Registration, login, OTP and password reset" },
    { name: "Profile", description: "Current user, settings, consents, notifications" },
    { name: "KYC", description: "Identity verification (BVN, NIN, liveness, documents)" },
    { name: "Investor", description: "Wallet, funding, investments, withdrawals, payouts" },
    { name: "Borrower", description: "Loan applications, loans, repayments, disbursement account" },
    { name: "Admin", description: "Operations workspace: users, loans, KYC, finance, content" },
    { name: "Payments", description: "Browser return pages for hosted payment flows" },
    { name: "Webhooks", description: "Provider webhook receivers" },
    { name: "Providers", description: "Provider reference data" }
  ],
  components: {
    securitySchemes: { bearerAuth: { type: "http", scheme: "bearer", bearerFormat: "JWT" } },
    schemas: {
      Amount: { type: "object", required: ["amountNaira"], properties: { amountNaira: { type: "number", example: 100000 } } },
      Error: { type: "object", properties: { ok: { type: "boolean", example: false }, error: { type: "string" }, code: { type: "string", nullable: true } } }
    }
  },
  paths: { ...healthPaths, ...authPaths, ...profilePaths, ...kycPaths, ...investorPaths, ...borrowerPaths, ...adminPaths, ...adminOpsPaths, ...paymentsAndWebhookPaths }
};
